- src/core/js/views/buttonsView.js
- src/core/js/views/questionView.js
See https://github.com/adaptlearning/adapt_framework/issues/430 for info.
> Add ability to turn off model answers for questions

- src/core/js/views/buttonsView.js
> amend onButtonStateChanged so that it uses the new button labels in course.json

- src/core/js/models/adaptModel.js
This enables componentModel.js to setup _isQuestionType
fixes #499
> Added init function back in

- config.js
- src/core/js/accessibility.js
- src/core/js/libraries/jquery.a11y.js
- src/core/less/base.less
Beginning of accessibility upgrade.
This is the inclusion of a general jquery accessibility plugin to help with global support of screen readers
Library: https://github.com/cgkineo/jquery.a11y 
@kirsty-hames @svenlaux
> ACCESSIBILITY: Add latest jquery.a11y to libraries

- Gruntfile.js
This is very similar to a previous change for themes to allow
selection of a specific menu, when more than one is installed.
> Fixes #516 - allows selection of specific menu

- src/core/js/accessibility.js
- src/course/config.json
- src/course/en/course.json
Course:
Added and amended aria-labels
Config:
Allowed a11y_text helper to be turned on/off via config.json (as per request @darylhedley)
> Accessibility - updated course and added functionality

- src/core/js/views/drawerView.js
- src/core/less/base.less
- src/core/less/reset.less
- src/course/config.json
Outstanding branch from the RTL work. Looks good from my tests.
> Add RTL support

- Gruntfile.js
Addresses #538: fonts folders of other plugins (not just theme) need to be copied during build.
> Add fonts folders to grunt copy and watch

- src/core/less/base.less
Two conflicting rules resolved 
https://github.com/adaptlearning/adapt-contrib-vanilla/pull/67
> Made focus rule uniform

- src/course/en/contentObjects.json
Along with this PR https://github.com/adaptlearning/adapt-contrib-boxmenu/pull/37
> Externalise the duration label

- src/course/en/course.json
Also see https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/37
> Add ariaLabels for pageLevelProgress

- src/core/js/router.js
It makes sense to implement a handler for this, since 'backButton' is
already supported.
> Resolves #565 - Implements 'navigation:homeButton'

- src/core/js/app.js
- src/core/js/models/adaptModel.js
- src/core/js/models/configModel.js
- src/core/js/models/routerModel.js
https://adaptlearning.atlassian.net/browse/ABU-493
> Removed locked attribute references

- adapt.json
- src/course/en/articles.json
- src/course/en/blocks.json
- src/course/en/components.json
- src/course/en/course.json
Added new assessment extension and results components to test course.
example: http://rawgit.com/oliverfoster/builds/assessment/index.html
> Assessment upgrade

- src/core/js/router.js
- src/core/js/views/adaptView.js
- Slightly refactored router.js
- Setting model._isReady to false on AdaptView initialize()
> Fixes #573 - Router struggles with nesting

- config.js
- src/core/js/adapt.js
- src/core/js/router.js
e.g:
index.html#/id/co-05
index.html#/id/c-85
index.html#/id/b-30
index.html#/id/a-10
etc
Also as requested by Ollie the offset of the navigation is taken into account in Adapt.navigateToElement.
> allowed navigation to any object via the location.hash

- src/core/js/helpers.js
https://github.com/adaptlearning/adapt_framework/issues/556
> Added math helper

- src/core/less/base.less
Added style amends for accessibility for use in theme version 2
> CSS theme update

- src/core/js/adapt.js
to ensure correct component gains focus
> BUGFIX: Focus on scrollto element

- src/core/js/libraries/jquery.a11y.js
> BUGFIX: safari + ipad duplicate elements

- src/core/js/libraries/inview.js
Based upon inview, performance increase + better accuracy. Implements 'inview' event, adds 'onscreen' event,
from https://github.com/cgkineo/jquery.onscreen
> Replaced inview with onscreen

- src/core/js/models/adaptModel.js
- src/core/js/models/contentObjectModel.js
PLP needs updating to display optional states.
We need some discussion around this.
https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/42
> Implemented _isOptional behaviour

- Gruntfile.js
- package.json
Also various minor housekeeping-related amends
> Add a help task to list out the available tasks

- src/course/en/course.json
https://adaptlearning.atlassian.net/browse/ABU-594
> Added aria label for the transcript button

- src/course/en/components.json
> Sentence case question buttons

- src/core/less/reset.less
fix to prevent accidental selection of text on touch devices.
> Stop all body text being selectable

- src/core/js/views/notifyView.js
> ABU-641: Allow escape to close notify if accessibility isn't on - Allow shadow click to close notify

- src/course/en/components.json
Related pr: https://github.com/adaptlearning/adapt-contrib-media/pull/106
> ABU-697 Inline transcript styling

- src/core/js/views/drawerView.js
> ABU-571: Added escape key to close drawer when accessibility is not on

- Gruntfile.js
Fixes https://github.com/adaptlearning/adapt_framework/issues/623
> Grunt update

- src/course/en/course.json
> Removed 'Select to view.' from menuItem ariaLabel

- src/course/config.json
fixes https://adaptlearning.atlassian.net/browse/ABU-878
> add _isEnabled property to config.json

- src/core/js/device.js
Found when running adapt in iOS uiwebview
> ABU-881: Fixed error when bowser can't find a detail

- Gruntfile.js
Fixes https://adaptlearning.atlassian.net/browse/ABU-884
> Fix copy:courseAssets and copy:courseJson to point to correct files

- src/core/js/models/adaptModel.js
- src/core/js/views/buttonsView.js
- src/core/js/views/questionView.js
* fix to buttonsview to remove marking classes properly
* isoptional fix to adaptmodel
* readability changes to adaptmodel and questionview
> General fixes and readability changes

- src/core/js/accessibility.js
- src/core/js/libraries/jquery.a11y.js
- src/core/js/views/drawerView.js
- src/core/js/views/notifyView.js
* moved scroll locking into drawer and notify explicitly
* allows hotgraphic popup to keep scrolling
> ABU-972: Stop scroll lock on hotgraphic popup

- src/course/en/course.json
https://adaptlearning.atlassian.net/browse/ABU-867
> Added aria-labels to indicate end of menu/page/PLP/resources.

- src/core/js/libraries/libraries.js
- src/core/js/models/adaptModel.js
- src/core/js/models/componentModel.js
- src/core/js/models/contentObjectModel.js
- src/core/js/views/drawerView.js
* ABU-700 - check if _isOptional section containers should be marked as completed on setup.
* ABU-790 - Fix drawer close vs scrollto timing
* ABU-710 -  Removed unneeded function from contentObjectModel.js
Should be checked with:
https://github.com/adaptlearning/adapt-contrib-assessment/pull/45
https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/54
https://github.com/adaptlearning/adapt-contrib-boxmenu/pull/47
> ABU-700, ABU-790, ABU-710

- Gruntfile.js
Fix issue with broken json check on multiple course folders
* also added missing ids check (referenced parents which do not exist)
> Fix gruntfile JSON Check

- INSTALL.md
README will not have install instructions.
> Initial commit of INSTALL.md

- Gruntfile.js
- package.json
https://adaptlearning.atlassian.net/browse/ABU-1002
> ABU-1002: properties.schema globals defaults > course.json

- adapt.json
> Add spoor, bookmarking to adapt.json

- .bowerrc
as per  https://adaptlearning.atlassian.net/browse/ABU-1020
> restored .bowerrc 

- src/core/less/base.less
Bug fix for no/touch so the focus guard functions.
> Hotfix for a11y Focus Guard

- src/core/js/views/notifyView.js
Please see: https://github.com/adaptlearning/adapt_framework/pull/716
> Changed height to outerHeight

- src/course/en/course.json
PLP and menu globals match respective handlebars templates.
Also remove some redundant aria labels.
> PLP and menu globals moved to plugin specific fields

- src/core/js/libraries/inview.js
- src/core/js/libraries/jquery.a11y.js
* jquery.a11y issue/16: trigger window.scroll on popup scroll https://github.com/adaptlearning/jquery.a11y@00c2db0
* jquery.onscreen issue/2: debounce scroll check https://github.com/adaptlearning/jquery.onscreen@166ba30
#696
> hotfix/696: jquery.a11y & jquery.onscreen update

- src/course/en/course.json
Global aria labels for PLP have been moved to _globals. _extensions. _pageLevelProgress. Fixes missing end of PLP aria labels.
> Move PLP globals to correct place

- src/core/js/views/questionView.js
https://adaptlearning.atlassian.net/browse/ABU-690
> Added SCORM interactions support.

- src/core/js/views/questionView.js
https://adaptlearning.atlassian.net/browse/ABU-690
> Added SCORM interactions support. See also adapt-contrib-spoor.

- package.json
> updated license name

- src/index.html
> a to button

- Gruntfile.js
> Add ability for server-build to generate source-maps

- src/core/js/views/notifyView.js
Amended trigger to target notify rather than its container
> Hotfix for Notify Focus Bug

- src/core/js/router.js
> re-added 'navigateToHomeRoute' function

- src/core/js/libraries/jquery.a11y.js
allow arrows keys to pass into input/select/textareas in a scroll-locked region
> keyboard fix

- src/core/js/views/questionView.js
https://adaptlearning.atlassian.net/browse/ABU-690
> Change default behaviour to record interactions.

- src/core/js/libraries/inview.js
Fixes issue where iOS doesn't recognise components completion. https://adaptlearning.atlassian.net/browse/ABU-1074
> Fix iOS PLP issue #ABU-1074

- src/core/less/base.less
> Invalid CSS fix

- src/core/less/base.less
Removed override as it was affected buttons that had not been converted from <a> tags. 
Removed content-box sizing as it was causing rendering errors with components such as the accordion item title.
> Removed base css and moved to buttons.less

- src/core/js/libraries/imageReady.js
See > https://github.com/cgkineo/jquery.imageready
https://adaptlearning.atlassian.net/browse/ABU-688
https://github.com/adaptlearning/adapt_framework/issues/542
https://css-tricks.com/snippets/jquery/fixing-load-in-ie-for-cached-images/#comment-98602
> ABU-688: Rewritten imageready

- src/core/js/router.js
jquery.fn.html cannot be used to change head elements in ie8. will through an error.
> bugfix: ie8 document title fix

- src/core/js/router.js
Brought forward from master branch.
> Added navigateToHomeRoute

- src/core/js/views/buttonsView.js
If you reset the model on an answered question component, it reset the feedback,
> Feedback button reset on component model reset

- src/core/js/views/drawerView.js
- src/core/js/views/notifyView.js
defer completion of show code until animation is finished
> ABU-1091: Drawer and Notify animation fix

- src/core/js/views/questionView.js
change `canShowModuleAnswer` to `canShowModelAnswer`
> correct typo

- src/core/js/views/accessibilityView.js
Refresh root route on accessibility enable
> ABU-1088 - Accessibility menu tabbing

- src/course/en/articles.json
- src/course/en/blocks.json
as per [readme](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/README.md)
> bugfix/course: moved assessmentResults to new article

- package.json
- src/course/en/articles.json
should be in the assessment contentObject (co-15)
> correct location of assessment results article

- src/core/js/views/adaptView.js
Throw informative error for components added to config.json which aren't installed.
Fixes #721
> resolve issue721

- src/core/js/views/drawerView.js
Fixes [ABU-799](https://adaptlearning.atlassian.net/projects/ABU/issues/ABU-799)
> Issue ABU-799

- package.json
- src/core/js/libraries/imageReady.js
see [ABU-1147](https://adaptlearning.atlassian.net/browse/ABU-1147)
> Hotfix for slow loading in IE9

- src/core/js/views/notifyView.js
Will allow ESC button to close the notification popup when the accessibility is not active rather than is not enabled!
> Allow ESC button to close the popup when accessibility is not active

- grunt/helpers.js
- grunt/tasks/help.js
Finally fixed up help task, although it now only loads the tasks in grunt/tasks, which may not be suitable (better than before, at least!)
> Couple of small grunt amends

- src/core/js/app.js
Defer plugin errors until adapt has loaded
fixed #915
> #915 Bad plugin resilience

- grunt/config/javascript.js
- grunt/tasks/javascript.js
@oliverfoster's fix for issue caused by includes.
> Fix issue with AT 'includes'

- src/core/js/models/adaptModel.js
> issue/923: remove isoptional cascade

- src/core/less/reset.less
Numbered / Ordered List Items were missing the styling that was in place for Unordered List Items
> adding styling for ordered list items

- src/core/js/libraries/inview.js
inview didn't register if area was flush with the top or the bottom of the window
this fixes that issue
part of issue #944
> issue-944: inview issues

- grunt/config/javascript.js
- grunt/tasks/javascript.js
> Javascript compilation: add support for filter

- grunt/helpers.js
> Change getIncludes to only get deps for included plugins

- grunt/config/replace.js
Also using path.join() now rather than string concatenation for folder names.
> Resolves #984, removes dependency on 'build' folder existing

- src/core/js/app.js
> Add better error message for failed initialisation of uninstalled components

- src/core/js/adapt.js
- src/core/js/models/adaptModel.js
- src/core/js/router.js
- src/core/js/startController.js
#906 
/*example
"_start": {
"_isEnabled": true,
"_startIds": [
{
"_className": ".size-small.touch, .size-medium.touch",
"_id": "co-05",
"_skipIfComplete": false
},
{
"_className": ".size-small.no-touch, .size-medium.no-touch",
"_id": "co-10",
"_skipIfComplete": false
}
],
"_id": "course",
"_force": true
},
*/
> issue/906: Added start controller

- src/core/js/scriptLoader.js
> Wait until JQuery gets loaded

- src/course/en/components.json
- src/course/en/video/c-40.vtt
* added cc file to course
* added closed captions and fullscreen to media
to go with https://github.com/adaptlearning/adapt-contrib-media/pull/139
>  issue-983: closed captions and fullscreen

- src/course/en/course.json
- Fixes #1001 
- should be merge with https://github.com/adaptlearning/adapt-contrib-resources/pull/37
> added `_isEnabled` for resources

- src/core/js/models/adaptModel.js
#806 LukaszGrela original pr
#804 Original issue
> issue-806: added _classes default

- src/core/js/models/adaptModel.js
- src/core/js/models/courseModel.js
> Add _isLocked to AdaptModel

- src/core/less/base.less
> default less-variables added

- src/course/en/course.json
> remove instruction from globals

- package.json
whilst bug in less@2.7.0
https://github.com/adaptlearning/adapt_framework/issues/1047
> issue-1047: downgrade less library

- src/core/js/helpers.js
* added sub template ``compile``, ``compile_a11y_text`` and ``compile_a11y_normalize``   helpers
* added ``compare`` helper
* renamed ``numbers`` to ``inc``
* added ``dec`` helper
* renamed ``lowerCase`` to ``lowercase``
* renamed ``if_value_equals`` to ``equals``
https://github.com/adaptlearning/adapt_framework/issues/1049
> issue-1049: helper amends

- src/core/js/libraries/jquery.a11y.js
@guywillis 
@chucklorenz 
to force #focuser not to read, need to amend trickle to put focus here on shift
> issue-1015: update #focuser to not read

- src/core/js/views/drawerView.js
when accessibility is not active (see #938)
> allow drawer to be closed by Esc keypress

- grunt/tasks/translate/exportFile.js
... when no data to write into a csv file
> fixes #1103 

- grunt/config/watch.js
- grunt/tasks/schema-defaults.js
Resolves https://github.com/adaptlearning/adapt_framework/issues/991 by reversing logic.
> Fix schema-defaults Grunt task

- src/core/js/views/questionView.js
New hook function `onSubmitted` - complementary to the `onCannotSubmit`
At the moment extending class needs to override `onSubmitClicked` when easier is to have a hook function to be overridden
> New hook function onSubmitted

- src/core/js/models/questionModel.js
To aid development for https://github.com/adaptlearning/adapt_framework/issues/1046.
> Add _canShowMarking to questionModel

- src/core/js/views/buttonsView.js
To fix change in https://github.com/adaptlearning/adapt_framework/commit/db4211cf7e301e899cfdcc15a5122329dcfc9fe6.
> Add missing bracket

- src/core/js/libraries/jquery.a11y.js
https://github.com/adaptlearning/adapt_framework/issues/1015
* redirect focus to #a11y-focuser when no other element found
> issue-1015: fix for jquery.a11y error

- grunt/config/less.js
https://github.com/adaptlearning/adapt_framework/issues/1160
* allow nested folders in preparation to include theme basic less
> issue-1160: expand less compiler for core

- grunt/tasks/create-json-config.js
https://github.com/adaptlearning/adapt_framework/issues/1167
allows the framework to compile when no theme is installed
> issue-1167: fix bug in create-json-config

- grunt/tasks/less.js
https://github.com/adaptlearning/adapt_framework/issues/1183
> issue-1183: order of less compile, variables first

- grunt/config/copy.js
https://github.com/adaptlearning/adapt_framework/issues/1185
> issue-1185: make core assets theme relative

- grunt/tasks/translate/loadLanguageFiles.js
- package.json
try to auto-detect language files encoding on import.
decode with detected character-encoding, fallback to utf-8
> decode languagefiles on import

- grunt/tasks/translate/loadLanguageFiles.js
check if there are either json or csv files in the languagefiles/<targetLang> directory
> autodetect import format

- adapt.json
> add adapt-contrib-languagePicker to dependencies in adapt.json

- grunt/config/watch.js
https://github.com/adaptlearning/adapt_framework/issues/752
> Fixes #752

- src/course/en/contentObjects.json
Resolves https://github.com/adaptlearning/adapt_framework/issues/1148.
> Banish durationLabel from content objects

- src/core/js/app.js
- src/core/js/drawer.js
Emits new event `app:languageChanged` with `language` as an argument.
> Move Language Picker loading into core

- config.js
- grunt/config/copy.js
- grunt/config/javascript.js
- grunt/tasks/javascript.js
- src/core/js/app.js
- src/core/js/scriptLoader.js
* moved all libraries out of compilation
* allowed all plugins to have a libraries folder
* allowed all plugins to have a required folder
* removed unneeded licensing comments
https://github.com/adaptlearning/adapt_framework/issues/1228
> issue-1228-1: speed up javascript compilation

- src/core/js/app.js
- src/core/js/offlineStorage.js
In conjunction with https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/12.
> Load course data via setting language

- config.js
- src/core/js/scriptLoader.js
i missed the odd reference to the bowser library. so this is to take it out of compilation also.
https://github.com/adaptlearning/adapt_framework/issues/1228
> issue-1228-2: removed bowser library from compilation

- src/core/js/drawer.js
- src/core/js/views/drawerView.js
first remove the existing drawerView on languageChanged event, then create a new instance
add custom remove method to drawerView
#1273
> fix drawer position during language change

- src/core/js/app.js
> fix direction issues when switching from rtl to ltr

- src/core/schema/contentobject.model.schema
- src/core/schema/course.model.schema
> add pageBody and description to model.schema files

- src/core/js/libraries/inview.js
fixes adaptlearning/adapt_framework#1299
Solution provided by Oliver Foster.
> inview Issue/1299

- src/core/js/adapt.js
- src/core/js/router.js
https://github.com/adaptlearning/adapt_framework/issues/1306
> issue-1306: added extra remove events

- src/core/js/libraries/inview.js
https://github.com/adaptlearning/adapt_framework/issues/1302
> issue-1302: updated inview library

- grunt/tasks/help.js
#1342 
get grunt help to ignore new "translate" folder
> issue-1342: fixed grunt help command

- src/core/js/device.js
add more screen related properties to Adapt.device object
> fixes issue/1331

- src/core/js/app.js
- src/core/js/scriptLoader.js
This allows loading.hbs in the theme to set the loading content.
> Reverts #1095

- src/core/js/app.js
- src/core/js/libraries/inview.js
- src/core/js/views/menuView.js
- src/core/js/views/pageView.js
* added allowScrollOver configuration in config.json
* trigger inview check after pageView:ready and menuView:ready
* fix inview force check on first measurement
* improved scrolled over calculations
config.json:
```json
"_inview": {
"_allowScrollOver": false
}
```
>  issue-1306: allowScrollOver + first-measure fixes

- src/core/js/helpers.js
https://github.com/adaptlearning/adapt_framework/issues/1347
* handle undefined template
* allow specified context
> issue-1347: updated compile helpers

- src/core/js/accessibility.js
- src/core/schema/config.model.schema
- src/course/config.json
> adds ability to disable accessibility for touch devices

- src/core/js/libraries/inview.js
From repo: https://github.com/adaptlearning/jquery.onscreen.
Resolves #1367.
> Update jquery.onscreen library

- src/core/js/models/adaptModel.js
> Add getAvailableChildren()

- src/core/js/accessibility.js
- src/core/js/device.js
- Added support for orientation-landscape and orientation-portrait classes
- Added new 'renderingEngine' property
- Added more advanced support for detecting the operating system
- Renamed Adapt.device.OS to Adapt.device.os
> Re-worked device.js to make use of Bowser 1.5 features

- src/core/js/accessibility.js
- src/core/js/router.js
- src/core/js/views/accessibilityView.js
- src/core/js/views/navigationView.js
- src/core/less/base.less
- src/core/schema/config.model.schema
- src/core/schema/course.model.schema
- src/core/templates/navigation.hbs
- src/course/config.json
add the ability to skip to menu or page main content bypassing the navigation links
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html
> Issue 1388

- README.md
Multi-language support seems like a "top feature" that should be promoted prominently.
> Added localisation feature to README

- src/core/js/app.js
- src/core/js/logging.js
- src/core/schema/config.model.schema
- src/course/config.json
pulling Ryan's changes into Adapt
> merge: irisEd/feature/logging_1399

- src/core/js/libraries/enum.js
- src/core/js/scriptLoader.js
fixes issue: https://github.com/adaptlearning/adapt_framework/issues/1429
library from: https://github.com/cgkineo/enum
> issue-1429: added enumeration support

- src/core/schema/course.model.schema
from `accessibilityToggleTextOn` and `accessibilityToggleTextOff`, fixes #1450
> remove underscore prefix

- src/core/templates/notify.hbs
Specifically this is required to render data-adapt-id as part of #1427.
> Added ability to output attributes on Notify

- src/core/js/device.js
- replace "." with "-"
- convert to lowercase
Old syntax kept in to maintain backwards compatibility.
> Turn browserstring into valid css classes

- src/core/js/libraries/jquery.a11y.js
> Add div[contenteditable=true] to native space elements

- src/core/js/router.js
Converted _isCircularNavigationInProgress to a boolean on the router object.
Added the pruneArguments() function and tidied up the passing of arguments.
Also corrected some minor indentation issues.
> Resolves #1472, corrects issue introduced in router.js

- src/core/js/models/questionModel.js
> issue-1482: wrong value

- src/course/en/course.json
> add _requireAssessmentPassed to the `_assessment` object

- src/core/js/startController.js
> issue-1484: start controller replace history

- src/core/js/views/notifyView.js
Removes it again  when closeNotify() runs.
> Resolves #1489 - Adds 'notify' class to HTML tag when invoked

- src/core/js/offlineStorage.js
This was never setting ready to true.
Converted tabs to spaces as well.
> Fixes problem with Adapt.offlineStorage not setting ready without Spoor

- src/core/js/accessibility.js
- src/core/js/adapt.js
- src/core/js/adaptCollection.js
- src/core/js/app.js
- src/core/js/device.js
- src/core/js/drawer.js
- src/core/js/helpers.js
- src/core/js/models/adaptModel.js
- src/core/js/models/articleModel.js
- src/core/js/models/blockModel.js
- src/core/js/models/componentModel.js
- src/core/js/models/configModel.js
- src/core/js/models/contentObjectModel.js
- src/core/js/models/courseModel.js
- src/core/js/models/lockingModel.js
- src/core/js/models/notifyModel.js
- src/core/js/models/routerModel.js
- src/core/js/notify.js
- src/core/js/popupManager.js
- src/core/js/router.js
- src/core/js/scriptLoader.js
- src/core/js/views/accessibilityView.js
- src/core/js/views/drawerView.js
- src/core/js/views/navigationView.js
- src/core/js/views/notifyPushView.js
- src/core/js/views/notifyView.js
> issue/1517: fixed bad references

- src/core/js/models/itemsModel.js
- src/core/js/views/adaptView.js
add core itemsModel
`_isActive` attribute is added to `_items` Array. This attributes are managed by funcitons defined in the itemsModel.
The setter functions trigger a change event `change_items:_isActive`. Views listen to this event and hande Dom updates. Plugins can use the functions on the itemsModel to manipulate the state of the Component.
also fixes:
#1505
> Added new ItemsModel to core

- src/core/js/device.js
> Restore .toLowerCase() on device properties

- src/core/js/libraries/imageReady.js
* refactored: easier to read, better function order, unified common behaviour
* improves speed of getElementsByCSSAttributeName
* image cache issues in firefox and chrome
* doesn't wait for missing images
* correctly reports timed-out images
* fetches background images when no img tags are present
> issue-1533: imageReady version 2017-05-09

- src/core/js/app.js
https://github.com/adaptlearning/adapt_framework/issues/1536
> Fix for plugins doing asynchronous work prior to adapt:initialize

- src/core/js/app.js
#1532 
* app:dataLoaded was being called twice
> issue-1532: removed double app:dataLoaded

- src/core/js/helpers.js
> issue/1572: fixed compile helper context

- CHANGELOG.md
- grunt/config/handlebars.js
- package.json
> issue/1577: fix handlebars filter for windows

- grunt/tasks/less.js
Was symlinking a plugin and the *.less files were not getting including in the build.
> Have **/*.less expand follow symlinks

- src/core/js/scriptLoader.js
#1633 added jqm to the libraries folder but it doesn't get loaded without this change.
> Ensure jQuery mobile gets loaded  - completes #1633

- src/core/js/libraries/inview.js
#1594 update to latest version
#1591 fix android setTimeout throttling
#1452 fix bookmarking negative area issue
* fixes android setTimeout throttling
* stop inview events propagating
* use window.innerHeight and width to calculate window size
* fixes negative area issue #1452
> issue/1594: updated inview to version 2017-07-11

- src/core/js/views/adaptView.js
Fixes vertical alignment issue for RTL course configuration described in https://github.com/adaptlearning/adapt_framework/issues/1670
> Fix #1670: RTL vertical align of components

- src/core/js/router.js
#1582 
originally from https://github.com/cgkineo/adapt-pageIncompletePrompt/issues/13
> issue/1582: _canNavigate after router:navigate

- src/core/js/libraries/jquery.a11y.js
#1722 
Allow more style elements when converting to accessible text
> Addresses #1722

- grunt/config/scripts.js
- grunt/config/watch.js
- grunt/helpers.js
- grunt/tasks/build.js
- grunt/tasks/dev.js
- grunt/tasks/diff.js
- grunt/tasks/scripts.js
- grunt/tasks/server-build.js
- plugins.json
> issue-1741: grunt - added plugin scripts task adaptpostbuild

- src/core/schema/article.model.schema
- src/core/schema/block.model.schema
- src/core/schema/component.model.schema
- src/core/schema/contentobject.model.schema
https://github.com/adaptlearning/adapt_framework/issues/1694
> Added _isHidden to schema files

- grunt/helpers.js
#1784
grunt now errors properly on a bad config.json
> issue/1784: grunt good error on bad config.json

- src/core/schema/article.model.schema
- src/core/schema/block.model.schema
- src/core/schema/component.model.schema
- src/core/schema/config.model.schema
- src/core/schema/contentobject.model.schema
- src/core/schema/course.model.schema
to:
* remove some ARIA labels that aren't used
* add the core property `_isVisible`
* improve usability through better titles and/or help text
see #1435
> updates to the core schema files

- src/core/js/views/buttonsView.js
- src/core/templates/buttons.hbs
> issue/1709 - Added support for accessibility to display remaining attempts

- src/core/js/startController.js
Issue - https://github.com/adaptlearning/adapt_framework/issues/1601
> removed IE8 hack

- src/core/js/adapt.js
- src/core/js/app.js
- src/core/js/router.js
- src/core/js/views/adaptView.js
- src/core/js/wait.js
> issue/1814: turn Adapt wait into hard API

- src/core/js/scriptLoader.js
> restore loadJQuery & checkJQueryStatus; update comments

- src/core/schema/article.model.schema
- src/core/schema/block.model.schema
- src/core/schema/component.model.schema
- src/core/schema/config.model.schema
- src/core/schema/contentobject.model.schema
from the AT's develop branch
part of #1435
> update to include the new _onScreen settings

- src/core/js/models/questionModel.js
- src/core/js/views/questionView.js
Also moved getResponseType() and getResponse() from questionView.js to questionModel.js.
> Resolves #1710, added getInteractionObject() to questionModel.js

- grunt/tasks/build.js
- grunt/tasks/dev.js
- grunt/tasks/diff.js
- grunt/tasks/schema-defaults.js
- grunt/tasks/translate/updateCourseData.js
#1777 
* fixes issue with translate task and schema defaults
> issue/1777: grunt fixed schema issue with translate task

- grunt/tasks/create-json-config.js
#1775 allow perform on ``%outputdir%``
#1774 stop unnecessary recursion
> issue/1775+1774: grunt fixs for create-json-config

- grunt/tasks/check-json.js
#1782 
check-json not respects outputdir config variable
> issue/1782: grunt check-json respects outputdir config

- src/core/js/libraries/jquery.a11y.js
https://github.com/adaptlearning/adapt_framework/issues/833
> removed use of accessible-text-block

- grunt/config/copy.js
#1781 
copy task now respects outputdir config
> issue/1781: grunt copy task respects outputdir config

- src/core/js/models/adaptModel.js
also refactored the code out into a separate function to remove duplication
> fixes a bug with  requireCompletionOf that was accidentally introduced in #1607

- src/core/js/models/adaptModel.js
> issue/1854: ie11 switched native [].find( to _.find([],

- src/course/en/articles.json
> added  "_suppressMarking"

- src/course/en/articles.json
Issue : https://github.com/adaptlearning/adapt_framework/issues/1809
> added _allowResetIfPassed attribute

- src/index.html
Fixes https://github.com/adaptlearning/adapt_framework/issues/1886
> Added "Adapt" to empty title element

- src/core/js/device.js
> issue/1890: added preResize and postResize

- src/core/js/adapt.js
> Trigger standard events on subsequent initialises

- grunt/config/replace.js
> issue/1867: grunt-replace filter null values

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
https://github.com/adaptlearning/adapt_framework/issues/1847
> issue/1847: added bug and contributing md

- src/core/js/helpers.js
> issue/1906: allow templates to access all course data

- src/course/en/course.json
> remove _assessment._requireAssessmentPassed from course.json

- grunt/tasks/schema-defaults.js
> issue/1916:Incorrect course data is loaded when language picker is used

- src/core/js/libraries/inview.js
#1602
https://github.com/adaptlearning/jquery.onscreen/pull/26
to test:
* check that inview still works
> issue/1602: drop inview ie8 support

- src/core/js/views/buttonsView.js
> issue/1937: reverted onButtonStateChanged

- src/core/js/scriptLoader.js
#1961 
* wait for document ready
* replace link to fix js sourcemap issue
> issue/1961: fixes css loading issues

- grunt/config/uglify.js
- src/core/js/views/notifyView.js
#1966 
* removed es6 `let` from notify as it breaks minification
* removed ie8 support from minification
> issue/1966: minification fixes

- src/core/js/models/questionModel.js
> Updated feedback to show title independent of title/display title of the component.

- src/core/js/accessibility.js
> issue/1975: bug fix misnamed argument

- src/course/en/components.json
as demonstration of #1876 
also remove `_partlyCorrect` for questions with only one possible answer
> add title to feedback

- src/core/js/libraries/jquery.a11y.js
#1977 
removed white-space from accessibility tabbable regions
> issue/1977: a11y: remove white-space tabbable regions

- src/core/schema/config.model.schema
> added _disableAnimationFor to config.model.schema

- grunt/tasks/translate/loadLanguageFiles.js
add details on csv parsing error, it can helps :) At least, it helped me.
> [Locale] add details on csv parsing error

- src/core/schema/config.model.schema
> remove _isEnabledOnTouchDevices and _shouldSupportLegacyBrowsers

- src/course/config.json
following changes from https://github.com/adaptlearning/adapt_framework/pull/1797
just parking for now as these need to be merged in as close to the v3 release of spoor as possible
> amend completion settings

- grunt/config/javascript.js
- grunt/tasks/javascript.js
#2009 
it should come out like this:
> issue/2009: unified less and js sourcemaps

- grunt/config/tracking-insert.js
- grunt/config/tracking-remove.js
- grunt/config/tracking-reset.js
- grunt/tasks/tracking-insert.js
- grunt/tasks/tracking-remove.js
- grunt/tasks/tracking-reset.js
>  issue/2006: tracking tasks respect outputdir

- src/core/js/helpers.js
> Added any and all helpers

- src/core/js/drawer.js
- src/core/js/views/adaptView.js
- src/core/js/views/menuView.js
fixes #2031 
plus a bit of a code-tidy
> adds a 'completed' class to the menu

- src/core/js/app.js
- src/index.html
also remove a v1 > v2 buttons hack that's no longer needed
> adds a 'dir' attribute and ensures it gets updated

- README.md
> Remove Travis badge from README.md

- grunt/tasks/schema-defaults.js
#2025 
made sure paths are joined appropriately.
> issue/#2025: grunt schema-defaults, fixed bad path separators

- src/core/js/adapt.js
#2073 
Added `Adapt.getViewClass(name);`
> fixes issue/#2073: added Adapt.getViewClass

- src/core/templates/partials/component.hbs
Issue https://github.com/adaptlearning/adapt_framework/issues/2069
> added fallback to mobile Instruction.

- src/core/js/views/notifyView.js
Copy of https://github.com/adaptlearning/adapt_framework/issues/1659 fix for Legacy branch.
As requested in https://github.com/adaptlearning/adapt_framework/pull/2110 thread.
> fix for closeNotify calling multiple times

- src/core/js/libraries/jquery.a11y.js
#2101
* Removed ios correction code as no longer needed
> accessibility: issue/#2101 - removed ios correction code

- src/core/js/views/notifyPushView.js
- src/core/js/views/notifyView.js
- src/core/templates/notify.hbs
- src/core/templates/notifyPush.hbs
resolves #2052 
screenshot of the Notify element HTML with this change applied:
> accessibility: add aria-roledescription and aria-modal attributes

- src/core/js/views/notifyView.js
#2132 
* switched notify focus to after animation
> accessibility: issue/#2132 notify focus after animation

- src/core/js/app.js
Fixed:https://github.com/adaptlearning/adapt_framework/issues/2143
> Expose framework version in DOM

- src/core/js/views/drawerView.js
#2138 
* Added aria-hidden to drawer when closed
> accessibility: issue/#2138 drawer screenreader

- src/core/js/accessibility.js
#2161
* removed code, deprecated in #2114
> accessibility: issue/#2161 removed redundant code

- src/core/less/base.less
#2163 
* Set to 0 to make intention clearer
> accessibility: issue/#2163 @focus-outline improve deprecated value

- src/core/templates/partials/component.hbs
> accessibility: issue/#2083 Fixed bad merge

- src/core/js/accessibility.js
#2158 
* Added helper for faux aria image
> accessibility: issue/#2158 faux aria image

- src/core/js/views/notifyView.js
> Correct issue that was preventing Notify popups from being closed

- CHANGELOG.md
- package.json
Updated CHANGELOG.md and bumped version in package.json.
> Version 3.2.1 Release

- src/core/js/models/questionModel.js
Helps with https://github.com/adaptlearning/adapt-contrib-mcq/pull/144#issue-205186822.
[`mcqModel.js`](https://github.com/adaptlearning/adapt-contrib-mcq/blob/454cd9324e90320b227af307e3c3c4aafbeb87ea/js/mcqModel.js#L129) will also need a `if (!this.has('_feedback')) return;`.
> Tidy setting of feedback

- src/core/js/models/adaptModel.js
> update findDescendantModels (and add getAllDescendantModels)

- src/course/config.json
- src/course/en/course.json
#2200 
* Removed all redundant labels and all labels created by the grunt process.
> accessibility: issue/2200 removed redundant aria from source

- src/core/js/views/notifyView.js
- src/core/js/views/questionView.js
#2251
* Set popup focus immediately
* prevent closeNotify from calling before showNotify finishes
> accessibility: fixes issue/2251

- src/core/js/views/componentView.js
#2269 
allowing both the element to be used for inview and the callback function to be specified, so as to allow for plenty of flexibility
> moved inview logic into ComponentView

- src/core/js/views/buttonsView.js
- src/core/schema/course.model.schema
- src/core/templates/buttons.hbs
- src/course/en/course.json
#2254 
* Added buttons view marking aria
#2241
> accessibility: issue/2254 Added buttons view and mcq marking aria

- src/core/js/views/notifyView.js
#2279 
This is in line with how onAlertButtonClicked() already works.
> Resolves #2279 - passes notifyView object to notify:* events

- src/core/js/models/adaptModel.js
- src/core/js/models/articleModel.js
- src/core/js/models/blockModel.js
- src/core/js/models/componentModel.js
- src/core/js/models/contentObjectModel.js
to fix #2240 
also remove call to `setOptional` from `setupModel` - it wasn't actually doing anything and we wouldn't want to be forcing children to be optional anyway
general tidy-up to:
* change `_.bind` to `Function.bind`
* improve comments
* use best version of `model.set` as appropriate
* remove unused variables
> re-write of findAncestor

- src/core/schema/article.model.schema
- src/core/schema/block.model.schema
- src/core/schema/component.model.schema
- src/core/schema/config.model.schema
- src/core/schema/contentobject.model.schema
> Make schema future-proof with authoring tool

- src/core/js/models/itemsQuestionModel.js
- src/core/js/models/questionModel.js
#1180
Moved and refactored McqModel into the core as a base for all multiple choice components.
Based upon QuestionModel and ItemsComponentModel.
>  issue/1180: Added ItemsQuestionModel and isInteractive

- src/core/templates/buttons.hbs
> add missing aria-label to buttons-marking-icon

- grunt/tasks/translate/loadMasterCourse.js
- grunt/tasks/translate/updateCourseData.js
#2300
Added config.json support to translate code.
> issue/2300: Config.json support to translate:import

- src/core/schema/course.model.schema
see https://github.com/adaptlearning/adapt_framework/issues/2320
> correct typo (legacy branch)

- src/core/schema/article.model.schema
- src/core/schema/block.model.schema
- src/core/schema/component.model.schema
- src/core/schema/config.model.schema
- src/core/schema/contentobject.model.schema
- src/core/schema/course.model.schema
Sister PR to https://github.com/adaptlearning/adapt_framework/pull/2307 for framework 2.
> Make schema future-proof with authoring tool 

- grunt/config/replace.js
This was checking a non-existent object.
> Fixes #2247 - Corrects error in Spoor 'adapt_manifest' replace

- CHANGELOG.md
- package.json
- src/core/schema/config.model.schema
> Made jquery.onscreen (inview) _allowScrollOver configurable

- src/core/js/libraries/jquery.a11y.js
> issue/2370: Fixed clickable links with a11y on

- src/core/schema/config.model.schema
> default _accessibility._isEnabled to true

- src/core/js/libraries/jquery.a11y.js
#2370 
* Don't wrap only clickable elements inside container
> issue/2370: Do not wrap blocks with only tabbable elements

- package.json
- src/core/schema/config.model.schema
- src/core/schema/course.model.schema
Fixes https://github.com/adaptlearning/adapt_framework/issues/2360
> Update theme editing options

- package.json
- src/core/schema/config.model.schema
- src/core/schema/course.model.schema
> Update theme editing options (legacy)

- src/core/templates/navigation.hbs
> remove class a11y-ignore from skip navigation button

- src/core/js/libraries/jquery.resize.js
- src/core/js/views/questionView.js
#2423 
* Force jquery.resize to recalculate height synchronously when `$(window).resize()`
* Have `questionView` force jquery.resize to recalculate height before disabling submit button.
>  issue/2423: synchronous resize before question submit

- src/core/js/libraries/jquery.a11y.js
#2440 
* Added `passive:false` to natively passive event attachment, where required
> issue/2440: Chrome bug - scrolling background

- src/core/js/libraries/jquery.a11y.js
> Backport #2467 to v3 - IE11 scrolling

- src/core/js/models/itemsQuestionModel.js
QuestionModel.reset was never being called.
`_userAnswer` isn't reset via `resetQuestionOnRevisit` but that doesn't directly affect this particular issue.
> Amend to fix #2474

- grunt/config/copy.js
- grunt/config/watch.js
Fixed #2441 and also changes the calling of copy task now it's only allowed to copying modified files.
> fixed #2441

- src/core/js/scrolling.js
fixes #2484 
* added set behaviour
> issue/2484 allow overridden jQuery.fn.offset to set

- src/core/js/libraries/jquery.a11y.js
fixes #2493 
* Render as text not html
> issue/2493: a11y_text to render text not html

- grunt/config/less.js
> Fix less file sort order resolves #2487

- src/core/js/a11y.js
- src/core/js/a11y/keyboardFocusOutline.js
#2530 
* Set _isFocusOutlineKeyboardOnlyEnabled default true
* Ignore keypress on input and textinput
> issue/2530: outline on key press improvements

- src/core/js/models/questionModel.js
Addresses issue: https://github.com/adaptlearning/adapt_framework/issues/2546
> Added _items to QuestionModel defaults

- src/core/js/views/menuView.js
- src/core/js/views/pageView.js
#2558 
* Added a wait queue around content object ready functions so that extensions can hold the loading screen until they are rendered correctly
* Lock inview until content object is ready so that inview doesn't trigger on initial text blocks until ready
> issue/2558 Added contentObject ready wait queue and inview ready lock

- src/core/js/models/adaptModel.js
* findDescendants
* getAvailableChildren
* getParents
As have all been deprecated since v2.2
> remove deprecated functions

- src/core/less/core/notify.less
fixes https://github.com/adaptlearning/adapt_framework/issues/2582
> Added opacity 0 to notify__popup

- src/course/en/components.json
Fixes https://github.com/adaptlearning/adapt_framework/issues/2587
> Removed duplicate accordion item

- src/core/less/core/notify.less
Fixes https://github.com/adaptlearning/adapt_framework/issues/2591
> Removed opacity, added visibility hidden to notify__popup

- src/core/js/views/notifyView.js
v5 PR https://github.com/adaptlearning/adapt_framework/issues/2580
Subview resize causes notify to recalculate scrolling.
> Notify subview resize fix

- grunt/helpers.js
#2577 
* Use grunt.file.readJSON instead of require to load JSON
> issue/2577 Use grunt.file.readJSON instead of require

- src/core/js/views/notifyView.js
v5 PR #2580
Fix for when items within a subview don't resize
> Subview resize bug fix

- src/core/js/views/questionView.js
Resolves https://github.com/adaptlearning/adapt_framework/issues/2606
> Added additional classes

- src/core/js/views/notifyView.js
v3 PR #2580
Subview resize causes notify to recalculate scrolling.
> Notify subview resize fix. Some code formatting included

- package.json
- src/core/js/models/adaptModel.js
> checkLocking for menu type children from setCustomLocking call

- src/core/less/core/button.less
https://github.com/adaptlearning/adapt_framework/issues/2627
> Button marking fix

- src/core/js/startController.js
Also added an event handler so that you can easily add a 'return to start' button with attribute `data-event="returnToStart"` to nav.hbs to get 'return to start' functionality
(As a next step, it'd be a good idea to include a 'show return to start button' as a configurable option in the `_start` configuration )
resolves #2541
(also changed double quotes to single)
> added 'returnToStartLocation' to startController

- src/core/js/views/notifyPushView.js
- src/core/less/core/notifyPush.less
- src/core/templates/notifyPush.hbs
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2640
> Notify push reintroduction

- .gitignore
- package-lock.json
#2642 
* Add package-lock with fixed LESS version to 3.10.3
> fixes issue/2642 adds package-lock with less 3.10.3

- src/core/schema/block.model.schema
> #1657 expose _sortComponents to authoring tool.

- src/core/templates/partials/component.hbs
> issue/2619: Omit the whitespace in the component

- src/core/js/headings.js
> amend headings.js to get it to listen for menuItemView:render event

- src/core/js/router.js
fixes #2677 
* Exposed router controller at Adapt.router and converted router to ES6
> issue/2677 Exposed router controller at Adapt.router, converted to ES6

- src/core/js/a11y/log.js
- src/core/js/logging.js
- src/core/js/router.js
- src/core/schema/config.model.schema
- src/course/config.json
fixes #2678 
* Added Adpt.log.removed and Adapt.log.deprecated and changed logging controllers to ES6
> issue/2678 Added Adapt.log.removed and Adapt.log.deprecated

- src/core/js/views/adaptView.js
fixes #2699 
* Converted AdaptView to ES6
* Reduced some overly complex code
Requires https://github.com/adaptlearning/adapt_framework/pull/2698
> issue/2669 Converted AdaptView to ES6

- src/core/js/router.js
- src/core/js/views/navigationView.js
- src/core/templates/nav.hbs
fixes #2669 
* Moved button event handlers to navigationView from router
* Forced navigation buttons to hide on render and show on when needed on routing
> issue/2669 Moved navigation handlers to navigationView, fixed buttons showing on first load

- src/core/js/models/adaptModel.js
> issue/2623 - fixes for scrolling in trickle

- grunt/helpers/Translate.js
#2736 
* CSV column count warnings and column truncation
* Delimiter detection, correction and warn
> issue/2736 Added columns count warning and delimiter detection

- src/core/schema/component.model.schema
> #1912 expose _isResetOnRevisit to authoring tool.

- src/core/js/models/itemsComponentModel.js
> prevent invalid value from being processed by setActiveItem

- src/core/js/models/itemsComponentModel.js
> prevent invalid value from being processed by setActiveItem (v4 version)

- src/course/config.json
> set _shouldStoreResponses to true

- src/core/js/views/contentObjectView.js
> issue/2770 Corrected typo in contentObjectView remove events

- src/core/js/helpers.js
#2764 
* `any` helper can now be used inline
* `all` helper can now be used inline
* `none` helper as inline and block
> issue/2764 Added none helper and made any+all inline&blocks helpers

- src/core/libraries/jquery.resize.js
#2782 
* Modified `force` check to account for type
> issue/2782 Fixed bug in jquery.resize

- src/core/js/views/notifyView.js
#2785 
[PR](https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/41)
> allowed to set extra attributes

- src/core/js/helpers.js
- src/core/schema/config.model.schema
- src/course/config.json
Related to feature request in this issue: adaptlearning/adapt_framework#2702
* Adds menuGroup aria label level
> Added menuGroup aria level support

- src/core/js/data.js
- src/core/js/models/courseModel.js
#2780 
* Removed `CourseModel` typegroup `course`
* Moved `Adapt.course` creation into data layer
> issue/2780 Removed CourseModel tight coupling

- src/core/js/a11y.js
#2807 
* Fix required for https://github.com/adaptlearning/adapt-contrib-graphic/pull/75 and https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/123
> issue/2807 Fixed normalize to return text stripped of html

- src/core/js/models/questionModel.js
- src/core/js/views/buttonsView.js
- src/core/js/views/questionView.js
- src/core/templates/buttons.hbs
#2796 
* buttons template so that correctness aria label doesn't appear immediately
* Question view `can-show-marking` class should appear when property is set
* `QuesitonModel.canShowMarking` return true if property set and component interaction is complete
> issue/2796 Minor additional fixes

- src/core/js/views/questionView.js
#2825 
* Convert `"false"` to `false`
> issues/2825 _isResetOnRevisit "false" string convertion

- src/core/js/views/componentView.js
resolves https://github.com/adaptlearning/adapt_framework/issues/2839
> ComponentView.setupInviewCompletion - use default parameters

- src/core/schema/article.model.schema
- src/core/schema/block.model.schema
> remove default value from article/block display title

- src/core/js/scrolling.js
#2849 
* Scroll offset with scrolling container
> issue/2843 Corrected offset in scrolling container

- src/core/required/adapt/js/scriptLoader.js
#2861 
* Changed scriptLoader.js to support underscore as a(n) umd module
> issue/2861 Support umd underscorejs

- src/core/js/device.js
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2865
* Amended js responsive screen size trigger
> Amend js responsive trigger

- src/core/js/scrolling.js
> Fix selector

- grunt/config/copy.js
#2875
Grunt build to include config.json while runnning with languages argument.
> issue/2875 - Grunt build to include config.json while runnning with languages argument

- src/core/js/adapt.js
- src/core/js/models/questionModel.js
#2884 
* Automatic detection of view-only question models
* Registered the abstract question model
> issue/2884 Automatic detection of view-only question models

- src/core/templates/article.hbs
- src/core/templates/block.hbs
- src/core/templates/page.hbs
as was already done for component.hbs in #2666 
fixes #2619
> remove whitespace from article/block/page

- src/course/en/components.json
seeing at it asks you to select a year it seems poor design to allow the learner to choose more than one answer!
I know it's only the OOTB content, but still...
> amend MCQ c-60 to allow only one selection

- src/core/schema/contentobject.model.schema
- src/course/en/components.json
- src/course/en/contentObjects.json
Reverts adaptlearning/adapt_framework#2947
> Revert "remove placeholder alt text + update schema alt text description"

- grunt/config/clean.js
> clean .cache from build folder on grunt build

- src/core/js/data.js
- src/core/js/models/adaptModel.js
- src/core/js/views/questionView.js
resolves #2825 
refactor to remove nested if..else statements from `checkIfResetOnRevisit` in questionView.js
> move conversion of _isResetOnRevisit from questionView.js to adaptModel.js

- src/core/js/data.js
- src/core/js/models/componentModel.js
fixes https://github.com/adaptlearning/adapt_framework/issues/2977
> reset _isStarted on language change

- src/core/schema/contentobject.model.schema
- src/course/en/components.json
- src/course/en/contentObjects.json
A cleaner PR to replace https://github.com/adaptlearning/adapt_framework/pull/2981
Resolves https://github.com/adaptlearning/adapt_framework/issues/2939
> remove placeholder alt text + update schema alt text description

- src/core/js/a11y/browserFocus.js
fixes #3007 
* Moved behaviour to prevent click behaviour above config check
> issue/3007 Fixed aria-disabled click when a11y disabled

- src/core/js/adapt.js
- src/core/js/router.js
- src/core/js/views/pageView.js
fixes #3014 
* `Adapt.deferUntilCompletionChecked` is now an async +/ callback function
* Moved reset on revisit check from PageView preRender to router before render
> issue/3014 Fixed reset on revisit completion cascade

- GRUNT.md
- grunt/tasks/compress.js
fixes #3005
improve description for task
> document grunt compress

- .eslintrc.json
- src/core/js/a11y.js
- src/core/js/a11y/popup.js
- src/core/js/a11y/scroll.js
- src/core/js/adapt.js
- src/core/js/data.js
- src/core/js/fixes/img.lazyload.js
- src/core/js/helpers.js
- src/core/js/models/lockingModel.js
- src/core/js/models/questionModel.js
- src/core/js/navigation.js
- src/core/js/offlineStorage.js
- src/core/js/router.js
- src/core/js/scrolling.js
- src/core/js/startController.js
- src/core/js/views/adaptView.js
- src/core/js/views/questionView.js
> Update ESLint's ECMAScript syntax version

- src/core/js/models/adaptModel.js
> Fix filter in Adapt.findRelativeModel

- src/core/js/a11y/browserFocus.js
fixes #3038 
* Made force click focus on the last parent, not the first
> issue/3038 Click focus last parent

- src/core/js/views/adaptView.js
fixes #3045 
* Make render wait for child additions before triggering postRender
> issue/3045 Wait for children before triggering postRender

- .eslintrc.json
- src/core/js/views/adaptView.js
Implements https://github.com/adaptlearning/adapt_framework/pull/2963#issuecomment-773214305.
> Update view properties on model change

- src/core/js/router.js
fixes #3061 
* Router uses `history.back` and `history.forward` to correct url appropriately when routing is blocked going forwards and backwards
Test with [adapt-pageIncompletePrompt](https://github.com/cgkineo/adapt-pageIncompletePrompt) to see in action
> issue/3061 Fixed router history

- src/course/en/course.json
> amend labels of correct answer toggle button

- grunt/tasks/less.js
> Write Less error to stderr

- src/core/js/a11y/popup.js
- src/core/js/views/drawerView.js
> fixes for bad PLP scroll

- src/core/schema/course.model.schema
> amend labels of correct answer toggle button (AAT schema)

- src/core/js/models/itemsQuestionModel.js
if the relevant globals haven't been added to course.json - for example if using v4.0.1 (or earlier) of MCQ or v5.0.2 (or earlier) of GMCQ
fixes #3089
> prevent handlebars error caused by ariaAnswer being undefined

- src/core/less/_defaults/utility.less
fixes #3094 
* Added visibility hidden to clearfix
> issue/3094 Added visibility hidden to clearfix

- src/core/libraries/inview.js
fixes #3098 
* [Inview out-of-bounds checking to remove scroll pre-check](https://github.com/adaptlearning/adapt_framework/pull/3099/files#diff-53632b9b287dce81b79827993d0cf262f89d524e88fdc845cee2a93880dbf0c2L545-L551)
* [Inview out-of-bounds to drop decimals in comparisons](https://github.com/adaptlearning/adapt_framework/pull/3099/files#diff-53632b9b287dce81b79827993d0cf262f89d524e88fdc845cee2a93880dbf0c2R569-R572)
* Inview linting issues
* [Clarified out-of-bound check by changing the variable language to represent out-of-bound top/left/bottom/right](https://github.com/adaptlearning/adapt_framework/pull/3099/files#diff-53632b9b287dce81b79827993d0cf262f89d524e88fdc845cee2a93880dbf0c2R560-R572)
> issue/3098 Fixed inview outofbounds check

- src/core/templates/buttons.hbs
> add aria-hidden to marking icon

- src/core/js/data.js
following a change in language (fixes #3111)
fix typo in comment
> don't force start page to redisplay

- src/core/js/views/drawerView.js
> allow drawerDuration to be 0

- src/core/js/device.js
> initialise device size & orientation checking earlier

- src/core/js/router.js
isInCurrentContentObject > isNotInCurrentContentObject
> correct name of constant

- grunt/tasks/javascript.js
> Fix JavaScript Grunt task

- grunt/config/javascript.js
- src/core/js/models/buildModel.js
- src/core/libraries/semver.js
- src/core/required/adapt/js/scriptLoader.js
fixes #3121 
* `Adapt.build.isFrameworkVersion(version);`
* `Adapt.build.isPluginInstalled(name, version);`
> issue/3121 Added fw and plugin version detection

- grunt/config/build-config.js
- grunt/config/copy.js
- grunt/config/json-minify.js
- grunt/config/jsonlint.js
- grunt/config/less.js
- grunt/config/replace.js
- grunt/config/tracking-insert.js
- grunt/config/tracking-remove.js
- grunt/config/tracking-reset.js
- grunt/config/watch.js
- grunt/helpers.js
- grunt/tasks/build-config.js
- grunt/tasks/build.js
- grunt/tasks/check-json.js
- grunt/tasks/create-json-config.js
- grunt/tasks/dev.js
- grunt/tasks/diff.js
- grunt/tasks/schema-defaults.js
- grunt/tasks/server-build.js
- grunt/tasks/translate/exportFile.js
- grunt/tasks/translate/loadCourseData.js
- grunt/tasks/translate/loadLanguageFiles.js
- grunt/tasks/translate/loadMasterCourse.js
- grunt/tasks/translate/saveCourseData.js
- src/core/js/app.js
- src/core/js/models/buildModel.js
...to allow course content files to be non-json file-types.
> Back-port #1684 to legacy

- grunt/config/javascript.js
#3173 
* Javascript task will check for newer jsx and js files before compiling
> issue/3173 Added jsx to grunt javascript newer config

- grunt/tasks/javascript.js
fixes #3184 
* Invalidate the bundler's file cache if a file is missing causing the long compilation process to occur but fewer compilation bugs
> issue/3184 Invalidate cache on missing files

- package.json
fixes #3188 
* Bumped babel-plugin-transform-amd-to-es6 to latest version
> issue/3188 Fix for compilation issues

- src/core/js/views/questionView.js
fixes #3211 
* No longer jumps on reset
> issue/3211 Added preventScroll to reset click

- grunt/helpers.js
- src/core/js/data.js
- src/core/js/models/configModel.js
fixes #3222 #3220 #3218 #3224 
forum issue https://community.adaptlearning.org/mod/forum/discuss.php?d=4066#p14964
* Reverted code to original
* `Adapt.build.get('availableLanguageNames')` from grunt
* Check lang search param against availableLanguageNames
> issue/3222-a Check available language names on lang search param

- src/course/config.json
- src/course/en/course.json
https://github.com/adaptlearning/adapt-contrib-core/issues/55
* Added _shouldSubmitScore to config.json:_completionCriteria
* Added _correctToPass to course.json:_assessment
> issue/55 Fixed defaults for _shouldSubmitScore

- src/course/en/components.json
resolves [#3077](https://github.com/adaptlearning/adapt_framework/issues/3171)
>  Amends to default course alt text

- .github/workflows/addtomainproject.yml
Part of (https://github.com/adaptlearning/adapt_framework/issues/3315)
New
- Contributing and issue template mds
- Git actions workflow for adding new issues and prs to the main project board
> New: Issue and pr project addition automation (Fixes #3315)

- src/course/config.json
fixes #3318
* Changed _ariaLabels to relative strings
refs https://github.com/adaptlearning/adapt-contrib-core/pull/163
> Update: _ariaLevels to relative strings

- src/course/en/course.json
fixes #3331
* Added default navOrder for skip, back and drawer buttons
Defaults reflect the schemas of https://github.com/adaptlearning/adapt-contrib-core/pull/239
> Fix: Added default navOrder for skip, back and drawer buttons (fixes #3331)

- Gruntfile.js
fixes https://github.com/adaptlearning/adapt-cli/issues/169
* Catch ECONNRESET error
> Fix: Guard against ECONNRESET issue

- src/course/en/course.json
fixes #3348 
* Moved _extensions default to the correct place
> Fix: Moved _extensions default to the correct place (fixes #3348)

- src/course/config.json
fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/386
ref: https://github.com/adaptlearning/adapt-contrib-core/pull/348
* Added new option for controlling `prefers-reduced-motion` support
> New: Added _isPrefersReducedMotionEnabled default config

- .github/workflows/test.yml
- cypress/e2e/tests/menuPage.cy.js
- test.js
> Failing tests check

- src/course/config.json
fixes https://github.com/adaptlearning/adapt_framework/issues/3375
ref https://github.com/adaptlearning/adapt-contrib-core/pull/316
* Added config for _submitOnEveryAssessmentAttempt
> Fix: Added config for _submitOnEveryAssessmentAttempt

- grunt/helpers/schema/Schema.js
#3491 
* Return early added to applyDefaults to protect against null values in AAT (fixes #3491)
> Fix: return early added to applyDefaults to protect against null values in AAT (fixes #3491)

- .github/workflows/test.yml
Part of #3499 
* Added manual trigger and nightly run (weekdays) to test runner
> Fix: Added manual trigger and nightly run (weekdays) to test runner

- .releaserc
- package-lock.json
- package.json
Addresses #3506 
* Moving semantic release config out of package.json into it's own file
* package-lock.json will now get automatically bumped along with package.json version
> Chore: Bumping some dev dependencies and tidy up

- test/e2e/commands.js
Addresses #3508 
* Added testContainsOrNotExists helper function for e2e tests
> Chore: Added testContainsOrNotExists helper function for e2e tests

- .eslintrc.json
- package-lock.json
- package.json
fixes #3521 
* Added correct module and config for linting cypress files with eslint
> Fix: eslinting for cypress (fixes #3521)

- test/e2e/commands.js
- test/e2e/helpers.js
Addresses #3532 
* Added stripHtml helper function for e2e tests
> Chore: Added 2 helper functions for e2e tests

- src/course/en/course.json
Fixes #3545 
* New ARIA labels for mandatory and optional content added
> New: Mandatory and optional ARIA labels added (fixes #3545)

- src/course/config.json
- test.js
Fixes #3611 
* Tightening glob pattern for FW-level tests
> Fix: Tightening glob pattern for FW-level tests

- src/course/config.json
#3638 
* _type attribute added to config.json (fixes #3638)
> Fix: _type attribute added to config.json (fixes #3638)

- package-lock.json
- package.json
Addresses #3664 
* npm audit fix of existing packages
* Updated some outdated packages
> Fix: npm audit fix of existing packages and updated some outdated packages [#3664]

- src/course/config.json
Fixes #3669 
* Add `_disablePageHeaders` to sample course's _config.json_
> Update: Add _disablePageHeaders to sample course config.json (fixes #3669)

- src/course/config.json
* Updates base JSON config file to the [latest spoor confnigurations](https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/example.json).
* Fixes: #3682
> Fix: Update base spoor settings (fixes: #3682)

- grunt/helpers.js
fixes #3692 
* Allow jsonext in adapt.json
> New: Allow jsonext in adapt.json
