package.json

Can't run course with the current handlebars version

Revert grunt-contrib-handlebars to ~0.5.11

---

src/course/config.json

_onQuizFailure is now _onAssessmentFailure in spoor.
See https://github.com/adaptlearning/adapt-contrib-spoor/blob/v1.1.6/js/adapt-contrib-spoor.js#L105
and https://github.com/adaptlearning/adapt-contrib-spoor/blob/v1.1.6/example.json#L12

hot fix for issue #506

---

src/core/js/helpers.js

if_value_equals helper does not pass context back when returning
block.inverse.
fixes #530

if_value_equals doesn't pass context back

---

src/core/js/accessibility.js
src/core/js/device.js
src/core/js/libraries/jquery.a11y.js
src/core/js/notify.js
src/core/js/popupManager.js
src/core/js/router.js
src/core/js/views/accessibilityView.js
src/core/js/views/buttonsView.js
src/core/js/views/componentView.js
src/core/js/views/drawerView.js
src/core/js/views/navigationView.js
src/core/js/views/notifyPushView.js
src/core/js/views/notifyView.js
src/core/js/views/questionView.js
src/core/less/base.less
src/index.html

Traps tab on accessibility button if accessibility isn't on
Adds accessibility instructions for screen readers
Fixes popupmanager and tabindexes on popup/popdown
Wraps tab around to top of page from the bottom
Integrates jquery.a11y into the handlebars templates so that text blocks can become tabbable
Adds accessibility state rendering to componentView (is currently missing the 'state' partial as it needs to be added to theme)
Allows aria-labels to be read across all devices
Expands LESS focus outline to include all focused elements
Maintains and improves .focused class for ie8
Adds _globals to all popup models
Fixes button states, question view, notify and drawer to allow all to become accessible
Next stage is templates, components and extensions.
Had to resubmit …

Accessibility integration 2

---

Gruntfile.js

Previously all Handlebars (*.hbs) template files were pulled in as part of
a build.  This could lead to inconsistent output when more than one theme
or menu was installed in the adapt_framework directory.

Fixes #550 - theme and menu templates are handled

---

src/core/js/views/pageView.js

With a filter=opactiy(1) on the page, ie8 has to filter each video frame and so causes a 100% processor problem.

Fix for leftover ie8 opacity filter

---

Gruntfile.js
package.json

- `grunt build` task should clean `build/adapt/js/adapt.min.js.map` file.
- also cleaning up some temporary files/folder generated by build process.

Feature grunt clean task

---

src/core/js/scriptLoader.js

@hrajotia it didn't work sometimes on a fast connection as it was before.
jquery would load before require and would not be available to scrollTo, velocity, backbone etc. 
it would works sometimes as jquery is a larger file than require and so require would load and execute before jquery, allowing jquery to 'define' itself and therefore allow jquery to be available to the other libraries.
i've rewritten so that it goes, json2, consoles, require (wait for load), jquery (wait for load), adapt

BUGFIX: Load jquery after require to allow for other libraries to require jquery

---

src/core/js/accessibility.js
src/core/js/libraries/jquery.a11y.js

Stop redirecting the tab key to the accessibility button if the user has scrolled or entered a native form element. 
@brian-learningpool This is a fix for stopping the tab key augmentation after a normal interaction.

Accessibility fixes

---

src/core/js/models/adaptModel.js

This resolves a potential issue with findDecendants() and getChildren() as
this property does not exist on components.  
Resolves #592.

Adds a check for _children being undefined

---

src/core/js/device.js

Allows the devices platform to be identified as 'PlatformUnknown' when 'Windows', 'Mac' and 'Linux' aren't specified.
In the case of Windows Mobile 8.1, "ARM" is the platform name (which is rather non-specific, all things considered) https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/platform

Unknown platform fix

---

src/core/js/adapt.js

Force scroll to use only y axis where necessary

---

src/core/js/views/buttonsView.js

This is a problem when you get questions right in the assessment where there is no feedback button. The submit button becomes disabled and the focus cannot move to the next element in its parent.
Have forced focus to go to component-state element if available.

Make sure focus goes to component state if both buttons are disabled

---

src/index.html

This was affecting older versions of IE.
This resolves #628.

Added missing 'id' attribute to index.html

---

src/index.html

We noticed an issue on iPad and iPhone, open a course using Safari click add to home screen option, and then click the website icon that is created on the home screen, it will launch the website using Safari, but the course will not open!
It worked once I made this fix , we have the following line of code instead `<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">`.

Fix issue with IOS (Add to home screen)

---

src/core/js/accessibility.js
src/core/js/device.js
src/core/less/base.less
src/core/less/reset.less
src/course/config.json

1. Moved body {} styling to a .no-select {} class.
2. Added 'size-small',  'size-medium' and 'size-large' class for respective device sizes to html tag.
3. Added '_disableTextSelectOnClasses' to config.json in _accessibility: {}
4. Extended accessibility code to compare the classes in the above attribute with the classes on the html tag when the device size changes. The class 'no-select' is added / removed to the html tag when a match is found.
5. By default no text selection is permitted, do we want 'no-select' on just touch devices?

ABU-695: Disable text selection configurable

---

src/core/js/notify.js
src/core/js/views/drawerView.js
src/core/js/views/notifyView.js

Scrollbars hidden for both drawer and notify to stop background content from scrolling whilst they are open.
Added: Wait for image loading in notify, fixed notify positioning.
Fixed animations for ie9+
No animations for ie8
NOTE: Must fade the page to white in order to hide the scrollbars and prevent the user from seeing a page jump, so have minimized the effect using fadeins.
TEST ON:
iphone4 ios7
ipad mini ios8
android chrome
winxp ie8
win8 ie11 + win8 ie11:ie9 mode
win8 ff
win8 chrome
blackberry

ABU-640: Notify and Drawer

---

src/core/js/models/adaptModel.js

Two fixes:
* Check for `undefined` (cherry-picked from master)
* Fix for #636

Hotfix develop/636 -- two fixes around getChildren()

---

src/core/js/models/adaptModel.js

This patch resolves the issue with precedence in that the ordering of the components.json could overide the _layout attribute.  This change assumes that a _layout of "left" should appear first.  In mobile views, if this was not handled in the theme this was not the case.

Resolves #636 - Corrects component _layout attribute issue

---

Gruntfile.js

Stop gruntfile having direct reference to adapt-contrib-spoor and allow the 'required' folder to be used by other extensions.

Made 'required' folder extension global

---

src/core/js/device.js

On ie browsers, adapt should give a class name (ie) to the html element, but in ie 11 latest adapt gives a class(internet explorer) to the html element, This fix will catch (internet explorer) in the string and replace it with (ie).

Fix for IE11, adding a class (ie) to html element.

---

src/core/js/libraries/jquery.a11y.js

mobiles:
* captures touchstart event for pageY offset
* captures touchend to clear touchstart event capture
* calculates movement deltaY from offset of touchstart event and touchmove event pageY properties, for iphone and android
desktops:
* calculates delta properly for ie, ff, chrome and safari

ABU-972: Fixed scrolling always locked on mobile

---

src/course/config.json

After the fixes for this feature has been merged to all question components and spoor extension I believe it is the time to add "_shouldStoreResponses": false  to the adapt framework.

Add _shouldStoreResponses to the config file

---

src/core/js/views/notifyView.js

Using `outerHeight` instead of `height` gets the height of an element *including* any padding added to it, making vertical alignment more accurate.

Changed height to outerHeight

---

src/course/en/components.json

In the assessments page, the trickle can be applied to block or article, not article only.
https://github.com/adaptlearning/adapt-contrib-trickle

Assessment, Trickle applied to block or article

---

src/core/js/adapt.js

Allows devs to more easily extend existing components, by making available existing templates. Currently you're forced to create a new template with the name registered by your component.
This allows you to do such things as:
```
var TextDerivitive = Text.extend({
template: "text",
...
});
```

Don't override template if already set

---

src/core/js/libraries/jquery.a11y.js

Fix aimed at keeping content centralised on screen to give context to surroundings

Hotfix for a11y limitedScrollTo Position

---

src/core/js/libraries/jquery.a11y.js

a jquery object is receiving a uid instead of the dom object, so saving and restoring dom object tabindexes is flawed.
need to change to assigning a uid to the dom object so that it's tabindex can be restored correctly.
change made.

ABU-1075 - store uid on dom object

---

src/core/js/adapt.js
src/core/js/app.js
src/core/js/models/lockingModel.js
src/core/js/models/routerModel.js
src/core/js/router.js

* changes Adapt object from _.extend({}, Backbone.Events) to Backbone.Model to accommodate run-time variables in a consistent way
* extended Backbone.Model to include optional attribute locking, the locking mechanism is one lock per plugin name, to set or unset
* added _canScroll to Adapt model to block Adapt.scrollTo function from performing the scroll (useful for block sliders when they should manage their own scrolling)
* made Adapt.get("_canScroll") a locked attribute
* made Adapt.router.get("_canNavigate") a locked attribute (to overcome brians issue (https://github.com/adaptlearning/adapt_framework/issues/587)
* extended router to block all navigation events when using Adapt.router.set("_canNavigate", false, { pluginName: "plugin" });
* made router block navigation events when …

ABU-674: Locking as optional utility

---

src/core/js/views/questionView.js

On reset,  the focus returns to the start question text.

Accessibility issue with question component reset button

---

src/core/js/libraries/inview.js

* retain $(window) object to reduce calculation time
* retain window height and width between resizes
* retain window scroll position between scrolls
* stop using jquery :visible and implement manually (huge speed improvements)
* added start on user mouse click down, touch start and key down interactions
* reduced calculation time from 250 milliseconds / 1000 elements to ~70 milliseconds / 1000 elements
* differentiated inview callback from onscreen callback triggered check
* increased responsiveness

updated inview library

---

src/core/js/router.js

to allow plugins to capture and defer routing without being aware of the parameters provided.
used in conjunction with:
``this.listenTo(Adapt, "router:navigate", arguments);``
``Adapt.router.set("_canNavigation", false, {pluginName: "name"});``
``//do something else here``
``Adapt.router.set("_canNavigation", true, {pluginName: "name"});``
``Adapt.trigger(Adapt, "router:navigateTo", arguments);``

Amends to navigateTo

---

src/core/js/views/questionView.js

Check if component and page are ready before allowing focus to be set by question component reset functions.
Set focus to beginning of question on invalid submit click.

ABU-1038: Accessibility reset checks

---

src/core/js/libraries/jquery.a11y.js

Cannot focus on disabled or removed elements when coming down from a popup. Fix finds the next focusable element and sets focus and scrolls.

bugfix/accessibility: popdown fix

---

src/core/js/adapt.js
src/core/js/router.js

1. Add missing ``break;``
2. When using an article/block/component id to navigate, should replace route with content object id. This is to preserve the history of the back button.

hotfix/router: missing break and navigateToElement fix

---

src/course/en/components.json

Since the correct answer is a single number and not a range, it is confusing to specify it using the `_correctRange` property (even though it does work). Therefore am changing this to the more appropriate `_correctAnswer` property.

amend to slider in c-80

---

src/core/js/accessibility.js
src/core/js/libraries/jquery.a11y.js

* redirect onFocusCapture of focused elements from proxy elements (label) or overlay elements (divs/span) to their correct tabbable element (input, button, a, etc)
* fix focusOrNext behaviour so that it finds the next focusable element in the entire document, not just the immediate next siblings
* allow elements to signal that they aren't effected by scrolling .focus (i.e. absolutely positioned to a fixed html tag)
* ignore errors if the element gaining focused is out-of-view (ie8, invalid error/warning)
* move some of the behaviour from a11y_iosFalseClickFix to onFocusCapture to lessen the need for the fix, make the fix specific and to make onFocusCapture more robust
* make sure popdown forces return to previous element
* make sure navigation aria label is visible when required

hotfix/ABU-1133: general accessibility fixes

---

src/core/js/scriptLoader.js

jquery doesn't support cors in ie8/ie9 like this and stops all json loading.
removed support for ie8+ie9

bugfix/ABU-1132: Remove CORS <=IE9

---

src/core/js/views/navigationView.js

Using a button selector is too specific, and different from how things worked pre v2.0.4.

Fixes #828, changed selector from button to [data-event]

---

src/core/js/device.js

Moved device:resize trigger until after setting Adapt.device.screenSize. This allows device:resize callbacks to have accurate screensize property states.

bugfix/deviceResize: fixed poor state

---

src/core/js/models/adaptModel.js

getParents returns a Backbone.Collection array from [0] first parent to [x] last parent or null
getParents(true) returns a Backbone.Collection array from [0] current model to [x] last parent or null

feature/adaptModel: added getParents

---

src/core/js/libraries/imageReady.js

- correctly added background image checks to the $images array
- fix firefox css absolute urls by removing the " or ' from the outside of the url declaration url("absolute")

bugfix/imageReady: fixed background image checks

---

src/core/js/models/adaptModel.js

* reworked event attachment from adapt.on to adapt.listento so that the model owns the event handler
* reversed the order of the complete event fires #927

bugfix/927: reverse order of completion events

---

src/core/js/adapt.js
src/core/js/app.js
src/core/js/models/componentModel.js
src/core/js/models/questionModel.js
src/core/js/views/adaptView.js

#925 
* added questionModel
* moved questionModel code out of componentModel into questionModel
* added code to optionally allow components to register their own model through the ``Adapt.register`` interface.
```
Adapt.register("name", { view: View, model: Model }); //new style
Adapt.register("name", View); //old style - still works fine
```
* changed component model creation to use a component specified model (if available), the questionModel or the componentModel where required (which, as a plus, means any view-only question components will automatically use the questionModel and need no reworking for this PR to fit)
* reworked require statements to AMD style
should be entirely unobtrusive
task following this:
* move questionView model code into questionModel
* provide backwards …

enhancement/925: allow component specific & standard question models

---

config.js
src/core/js/scriptLoader.js

* removed explicit conversion of module declarations to "coreJS" style from "core/js" (+models, views etc)
* remapped current require("coreJS/adapt) style to "core/js/adapt" in grunt
* remapped current require("coreJS/adapt) style to "core/js/adapt" in browser
#929
actions to follow:
* convert all old require declarations from "coreJS" style to new "core/js/" style
* new new grunt requirejs task needs to be compatible with this style
should be unobtrusive as the old style can be remapped to the new style until we've converted everything.

enhancement/929: remove core require mappings "coreJS" "coreViews"

---

src/core/js/views/notifyView.js

#949 
Allows extensions like trickle to monitor notify popups correct.

issue/949: notify:opened and notify:closed triggers

---

src/core/js/router.js

This makes it consistent with the other navigation functions.

Resolves #961, adds check on _canNavigate to navigateToParent()

---

grunt/helpers.js

Two 'count' variables were causing a problem with the loop.

Resolves #969, corrects loop bug in Grunt getIncludes() helper

---

grunt/config/replace.js
grunt/tasks/build.js
grunt/tasks/dev.js
grunt/tasks/server-build.js
package.json
src/course/en/course.json

This is required to support upcoming work on the xAPI plugin but will also work with a slightly modified Spoor plugin.  The placeholder format is: @@property.
Right now properties from config.json and course.json are supported.
Squashed commit messages:
- Added replace task to build.js and dev.js
- Added support for passing both course and config to replace call
- Added 'description' to course.json.  This attribute is useful for the SCORM and xAPI extensions.
- Added shim for missing xAPI property. This is to cover edge cases where the xAPI extension may be defined but its configuration may be incomplete.
- Added a warning mesage for when xAPI activityID has not been set.  The course will not confirm to the spec if this has been left empty.

Added support for string substitution in XML files

---

src/core/js/models/adaptModel.js

#910 
if you need all of the mandatory components to be complete use _requireCompletionOf: -1  (this is as default)
if you need to exclude some of the mandatory components from completion use _isOptional: true (making them non-mandatory)
if you need only X number of mandatory components to complete, use requireCompletionOf: X

issue/910: added requireCompletionOf: X

---

src/core/js/models/adaptModel.js
src/core/js/models/blockModel.js

Added a snippet of code which allows you to override the left/right sort order of components by applying '_sortComponents': false to the container block.
Ideally used for when you have an MCQ component left aligned and Graphic component right aligned on desktop but want the Graphic component to appear above the MCQ in mobile view. 
All component JSON is unchanged, only amendment is to define the right aligned Graphic component above the left aligned MCQ component in the components.json.

Added layout sort override

---

src/core/js/views/notifyView.js

#1009 
To allow plugins to capture all exits from a notify

issue-1009: notify:cancelled event added

---

grunt/config/replace.js

The grunt-replace module would fail if undefined or null values were passed.  Passing a smaller list of course and config properties reduces the chances of that, and will speed up performance.

Resolves #1021, passes a subset of attributes to Grunt replace task

---

src/core/js/models/adaptModel.js

also refactor code so that we don't have to hide the call to `checkLocking` inside `checkCompletionStatus`
fixes #1025

remove one of the calls to checkLocking to avoid a warning appearing in the console

---

src/core/js/adapt.js
src/core/js/models/configModel.js
src/core/js/router.js
src/core/js/startController.js
src/core/js/views/questionView.js

This prevents routing to a locked page/menu via the URL, or menu link which has not yet been updated to support _isLocked.
Also, Adapt.findById() has been updated to return a warning when the _id value passed in does not exist in the mapping.

Resolves #1017, checks _isLocked in router

---

src/core/js/models/adaptModel.js
src/core/js/models/questionModel.js
src/core/js/views/questionView.js

#967 
Work done:
* all model code removed from questionView to questionModel
* compatibility layer for question components which still use their view to define model behaviour
Outcome:
* all questions can now have a proper model with defined behaviour
Next:
* ~~i'll do a pr for mcq and gmcq in this style before the end of the day~~  
https://github.com/adaptlearning/adapt-contrib-gmcq/issues/95  
https://github.com/adaptlearning/adapt-contrib-mcq/issues/120  
* just need to check that this makes sense to everyone (aside from the compatibility layer - which could be a bit confusing)  
* needs a lot of testing with current question components
To test backwards compatibility:
* download enhancement-967 of the framework
* run ``adapt install`` and ``npm install``
* run ``grunt dev``
To test …

enhancement-967: questionView model code > questionModel

---

src/core/js/libraries/jquery.a11y.js

Remove tabindex from hideable elements on popdown

jquery.a11y tabindex fix

---

src/core/js/device.js

When content is rendered inside frames, the wrong size classes were being applied for iOS devices.  Switching to use screen.width as part of the calculation resolves this.
Android devices already behave as expected.

Resolves #1096, device width for iOS devices

---

src/core/js/views/questionView.js

standard question view (new version) functions were not being called by the compatibility layer.
the checking statement, line 484, was checking if the required function on the current view prototype was the same as the compatibility layer function - which it always will have been because the compatibility extension view was always an extension of the question view.
i have stopped the compatibility extension including the question view prototype functions when the comparison takes place so that line 484 will not be comparing "setQuestionAsSubmitted" and "checkQuestionCompletion" to itself.

bugfix: #1114

---

src/core/js/app.js
src/core/js/models/courseModel.js
src/core/js/views/navigationView.js

for enhancement https://github.com/adaptlearning/adapt_framework/issues/1120
this is needed so that we don't have to duplicate code in the language picker

issue-1120: exposed loadCourseData

---

src/core/js/views/buttonsView.js

Avoids changing classes on buttons if `_canShowMarking` is false.
Original issue: adaptlearning/adapt_framework#1046.

Hook buttonsView into _canShowMarking

---

grunt/config/copy.js
grunt/config/jsonlint.js
grunt/config/watch.js
grunt/helpers.js

To build specific language folders: grunt build —languages=“fr,de”. Accepts comma separated list of language folders.
Requires https://github.com/adaptlearning/adapt_framework/pull/1039 to deal with multi lang tracking ID's.

Add grunt languages option

---

src/course/en/course.json

Following the fix to the schema-defaults Grunt task in https://github.com/adaptlearning/adapt_framework/pull/1101, this PR resolves the apparent inconsistencies between the source and build globals.

Refresh globals in course JSON

---

grunt/config/translate.js
grunt/tasks/translate.js
grunt/tasks/translate/exportFile.js
grunt/tasks/translate/loadCourseData.js
grunt/tasks/translate/loadLanguageFiles.js
grunt/tasks/translate/loadMasterCourse.js
grunt/tasks/translate/loadTranslateConfig.js

`grunt translate:export [--masterLang=en] [--format=json|raw|csv]`
defaults to :
--masterLang=en
--format=json
`grunt translate:import [--masterLang=en] --targetLang=de [--format=json|raw|csv] --replace`
required:
--targetLang
defaults to:
--masterLang=en
--format=json
**export:** grunt creates a lang folder namen like masterLang in languagefiles dir and exports the languagefiles in this dir
**import:** you must create you a folder named like your targetLang and add the translated file(s) into this dir
all csv/json files in the targetLang folder are read and parsed. so it should only contain one file for each a,b,c,course,co
When grunt translate:import is called, it checks now if there is already a folder in src/course named like targetLang. If there is one, it breaks unless the user adds …

grunt translate refactor

---

src/core/js/router.js

If the start controler is enabled, and '_force' is set to true, it should not be possible to route to the menu.

Corrects #1152 with start controller functionality

---

src/core/js/models/questionModel.js
src/core/js/views/buttonsView.js

A new checkFeedbackState() function has been added to buttonsView.js.
This is dependent on the theme implementing the 'no-feedback' and 'buttons-action-fullwidth' classes.

Resolves #1073, adds support for hiding 'Feedback' button

---

src/core/js/accessibility.js

https://github.com/adaptlearning/adapt_framework/issues/1051
* added ```a11y_attrs_heading(level)``` - for defining header attributes correctly
```handlebars
<div class="menu-title-inner h1 accessible-text-block" role="heading" aria-level="1" tabindex="0">
{{{displayTitle}}}
</div>
```
```handlebars
<div class="menu-title-inner h1 accessible-text-block" {{{a11y_attrs_heading 1}}}>
{{{displayTitle}}}
</div>
```
* added ```a11y_attrs_tabbable``` - for defining tabbable attributes correctly
```handlebars
<div class="menu-title-inner h1 accessible-text-block" role="region" tabindex="0">
{{{displayTitle}}}
</div>
```
```handlebars
<div class="menu-title-inner h1 accessible-text-block" {{{a11y_attrs_tabbable}}}>
{{{displayTitle}}}
</div>
```
* added ```a11y_aria_label``` - for defining aria …

issue-1051: added accessibility helpers

---

grunt/config/less.js
grunt/tasks/build.js
grunt/tasks/dev.js
grunt/tasks/less.js

https://github.com/adaptlearning/adapt_framework/issues/1159
added ```@adapt-device-small, @adapt-device-medium @adapt-device-large``` to less straight from theme.json
removes the need to specify screen widths in both json and less.

issue-1159: add screenSize from theme to less

---

src/core/js/views/questionView.js

Question View:
1. setupFeedback https://github.com/adaptlearning/adapt_framework/blob/cd2b27ba2c5df4e6f4c60ba15cacd4b769d9cfa2/src/core/js/views/questionView.js#L429-L447
2. markQuestion https://github.com/adaptlearning/adapt_framework/blob/cd2b27ba2c5df4e6f4c60ba15cacd4b769d9cfa2/src/core/js/views/questionView.js#L397-L410
Both functions should be called through the view always in compatibility mode as some of their sub functions can live on the view only
#1187

issue-1187: matching partial feedback fix

---

src/core/js/device.js

- Abstracted code into a getScreenWidth() function
- Corrected issue with width reported for iOS devices in landscape by adding getAppleScreenWidth() function

Rework to device.js

---

grunt/tasks/translate/exportFile.js
grunt/tasks/translate/loadCourseData.js

My suggestion is to remove the encoding detection on export since it is causing issues rather than solving them. We should make the assumption that the user starts with UTF-8-encoded JSON.
Export
* Write to UTF-8-encoded CSV or JSON.
* If CSV, add a byte order mark so that Excel (2007+) recognises it as UTF-8.
Excel
* On Windows, Excel defaults to saving in Windows-1252 encoding, which includes standard accented and extended punctutation [characters](https://en.wikipedia.org/wiki/Windows-1252#Code_page_layout), e.g. `á`, `’`, `–`, so nothing should be garbled from Adapt's default JSON.
* The user will have to follow [workarounds](http://stackoverflow.com/questions/4221176/excel-to-csv-with-utf8-encoding) if they want to save out a CSV from Excel in true UTF-8 encoding since this is a …

Remove encoding detection on export

---

src/core/js/views/accessibilityView.js

The Turn Accessibility On button doesn't have a state to the screen reader as it uses button text and an aria label.
As there was no state indicator in aria-label I've added the `toggleText` value to the end of it.
Issue https://github.com/adaptlearning/adapt_framework/issues/1172

Added toggle state label

---

grunt/config/tracking-insert.js
grunt/config/tracking-remove.js
grunt/config/tracking-reset.js
grunt/tasks/tracking-insert.js
grunt/tasks/tracking-remove.js
grunt/tasks/tracking-reset.js

resolves #370 
updated to use globbing pattern for multiple language folders
gets applied to all matching blocks.json and course.json files, so there is no way to execute on one specific language. Please add a comment if you think this is missing.

multilang grunt tracking-id's

---

grunt/tasks/translate/createLookupTable.js

Currently array's without items attribute are not supported. Example for this is `"inputType": "List"` used for lockedBy attribute.
Handle this case by skippinkg to next item.
If list of array needs to be supported, use array + items definition instead. E.g. textinput `_items._answers`

issue #1219 

---

src/core/js/accessibility.js

Fix issue #1241 - a11y calculates component to be out of view from additional px added.

Remove additional px from topOffset variable

---

src/core/js/app.js
src/core/js/startController.js

changed format in require paths
refactored startController for better code reuse
when a new language is loaded, either navigate to startHash created by startController or default location

startController fix for multilang courses

---

src/core/js/app.js
src/core/js/startController.js

Currently, unless `_force` is set, when you change language, you always end up back at `/#`. Because the course is being reset, you should follow the route specified in the `_start` configuration - even when `_force` is not set

 fix to ensure that the _start route is respected when changing language

---

src/course/en/blocks.json

add startText label to trickle buttons so that the export task can get the value and add to the language files
fixes #1282

add startText to trickle button

---

src/core/js/adapt.js
src/core/js/app.js
src/core/js/drawer.js
src/core/js/views/drawerView.js
src/core/templates/navigation.hbs

This appears to be because the drawer listens to the "adapt:initialize"
before checking that it has no items and should be hidden.
Since "adapt:initialize" should not be triggered more than once, I've added
a 'forceCheckVisibility' flag which forcees this check when the language
changes.

Corrects issue with phantom drawer displaying on a language change

---

grunt/config/copy.js

Replacing the **/* wildcard with the specific folder names to search in for the 'required' and 'libraries' folders.

Resolves #1312, performance improvement for Grunt copyMain task

---

grunt/config/replace.js

It appears that when the replace task is loaded, it immediately goes and searches for the config JSON file, but that file isn't built yet.
Parsing the config JSON needs to be deferred until the replace task executes.
(refer to issue #1324)

Defers parsing the config JSON until the replace task runs (fixes #1324)

---

src/core/js/libraries/es5-shim.min.js
src/core/js/scriptLoader.js
src/index.html

I've added the shim from https://github.com/inexorabletash/polyfill/blob/master/es5.js.
This provides implementations for:
- Object.getPrototypeOf
- Object getOwnPropertyNames
- Object.create
- Object.defineProperty
- Object.defineProperties
- Object.keys
- Function.prototype.bind
- Array.isArray
- Array.prototype.indexOf
- Array.prototype.lastIndexOf
- Array.prototype.every
- Array.prototype.some
- Array.prototype.forEach
- Array.prototype.map
- Array.prototype.filter
- Array.prototype.reduce
- Array.prototype.reduceRight
- String.prototype.trim
- Date.now
- Date.prototype.toISOString

Added ES5 shim for IE 8

---

src/core/js/views/adaptView.js
src/core/js/views/articleView.js
src/core/js/views/blockView.js
src/core/js/views/componentView.js
src/core/js/views/menuView.js
src/core/js/views/pageView.js

see #1380
also switch to AMD style module definitions, stop using shortcut paths
move concatenation operators from beginning of lines to end of lines as JSHint's recommendation

add a data-adapt-id attribute to the HTML for pages, menus, articles, blocks + components

---

src/course/en/course.json

As per @moloko comment on https://github.com/adaptlearning/adapt_framework/pull/1390#issuecomment-277016981

adding skip navigation Aria labels to sample course.json

---

src/core/js/adapt.js

This fix addresses an issue when navigating to components via page-level progress in certain circumstances. If the component description aria-label is aligned to the top of the component div (as happens in certain art directions), Adapt.scrollTo would centre the top of the component within the viewport rather than at the top of the viewport. N.B. this issue is normally only replicable when accessibility has been activated.

Fix for Adapt.scrollTo 'jump' bug

---

src/core/js/app.js
src/core/js/logging.js
src/core/js/scriptLoader.js
src/core/schema/config.model.schema
src/course/config.json

same as https://github.com/adaptlearning/adapt_framework/pull/1405 but with ie8 support
Note:
ie8 will not add spaces for ``console.log("a","b","c")`` style output. So it will read ``"abc"`` and not ``"a b c"`` as with more modern browsers.

Logging Module

---

grunt/config/javascript.js
grunt/config/less.js
grunt/tasks/diff.js
package.json

This task is a dev rebuild, checking if files are newer and recompiling if necessary.
It doesn't do a watch or a clean.
Only performs a check on LESS, Handlebars and JavaScript

issue-1233: added grunt diff

---

src/core/js/router.js

- arguments were being parsed as args but raw arguments are still passed to functions
- The code assumed that only the last argument may be null, this is not necessarily the case
- Plugin routing via the handlePluginRouter function did not appear to reset the _canNavigate property in the same way the handleId function does
- Tidied the check on _isCircularNavigationInProgress

Resolves #1458, corrects various issues with router.js

---

grunt/config/copy.js

Extending the solution used for 'required' and 'libraries' I've modified the copy routines for assets in components, extensions and menus. The regex used prevents the folder assets itself to be copied into the build assets.

Resolution to the #1463

---

grunt/tasks/create-json-config.js
grunt/tasks/less.js
grunt/tasks/schema-defaults.js
grunt/tasks/tracking-insert.js
grunt/tasks/tracking-remove.js
grunt/tasks/tracking-reset.js
grunt/tasks/translate/exportFile.js
grunt/tasks/translate/saveCourseData.js

issue: https://github.com/adaptlearning/adapt_framework/issues/1461
* create-json-config and schema-defaults both inadvertently strip the whitespace from the course.json and config.json files making them unreadable, i've added spaces 4 pretty print
* have swapped all occurrences of JSON.stringify to use  (json, null, integer)

issue-1461: stop grunt stripping whitespace from json

---

src/core/js/device.js

This is added in addition to the 'internet explorer' class.

Added 'ie' class for Internet Explorer 10 and 11

---

src/core/js/libraries/jquery.a11y.js

as it is preventing the select2 library used by [adapt-contrib-matching](https://github.com/adaptlearning/adapt-contrib-matching) from making sure only one `<select>` control can be open at once - fixes #1541

remove the call to event.stopPropagation

---

src/core/js/app.js
src/core/js/router.js
src/core/js/views/navigationView.js

fixed #1521 
1. allow default navigation bar to be disabled ```course._navigation._isDefaultNavigationDisabled```
2. add ``navigation:initialize`` event for navigation bar plugins to know when to start
3. put ``#wrapper`` location classes on ``html`` tag to allow styling of navigation as usual
4. insert ``.navigation`` container before the ``#wrapper`` div so that the tab order is preserved

issue/1521: remove navigation from #wrapper

---

grunt/config/handlebars.js

While developing plugins I will often symlink the plugin in to a test bed course. The grunt task for compiling templates was not following the symlink. This minor change addresses the issue.
https://github.com/isaacs/node-glob#options

Follow symlinks when building templates

---

src/core/js/helpers.js

#1545 
Handlebars.compile doesn't handle String objects. Handlebars "this" is always an Object.
This code converts incoming templates to string literals

issue/1545: String to literal compile helper

---

src/core/js/accessibility.js
src/core/schema/config.model.schema
src/course/config.json

issue-1519: default disable a11y on touch devices

---

grunt/config/copy.js
grunt/config/handlebars.js

The includedFilter() helper function would cause problems by running the filter on essential core files.  This affects the authoring tool where the config.json contains the list of plugins to include.

Fixes #1564 - Ensures core assets, fonts and templates are copied

---

src/core/js/device.js

Scroll events were triggering this due to the position of the address bar.  Given that the viewport size hasn't really changed this commit compares the height and width before and after the event, and only triggers device:resize if either have changed.

Fixes #1561, corrects 'device:resize' on iOS devices

---

src/core/js/router.js

circular navigation is when a course changes the url when it's not allowed to, the url must be corrected.
fixes https://github.com/adaptlearning/adapt_framework/issues/1582

issues/1582: fixed circular routing control reset

---

src/core/schema/article.model.schema
src/core/schema/block.model.schema
src/core/schema/component.model.schema
src/core/schema/config.model.schema
src/core/schema/contentobject.model.schema
src/core/schema/course.model.schema

see adaptlearning/adapt_authoring#1380
**please leave unmerged until all core plugins have been updated**
If approved, these changes will need to be copied to the authoring tool repository - as the framework's copies of the core schema files are only used for the 'export for translation' feature of the framework.

schema amends: change boolean selects to checkboxes 

---

src/core/js/libraries/imageReady.js

issue: https://github.com/adaptlearning/adapt_framework/issues/1641
source: https://github.com/adaptlearning/jquery.imageready
fixed:
* ie9-11 cached images not firing load event

issue/1641: update imageReady to latest

---

src/core/js/logging.js

... when a matching method is available e.g. `Adapt.log.error('this is an error')` will use `console.error` in browsers that support it - but `Adapt.log.fatal('doh!')` fall back to using `console.log`

amends logging module to use matching methods of the console object

---

src/core/js/drawer.js

Example of ordering resources extensions in course.json:
"_resources": {
"_isEnabled": true,
"_drawerOrder": 1,
"title": "Resources",
"description": "Click here to view resources for this course",
"_filterButtons": {
"all": "All",
"document": "Documents",
"media": "Media",
"link": "Links"
},
New drawerObject to be defined in extension js e.g. adapt-contrib-resources.js:
var drawerObject = {
title: courseResources.title,
description: courseResources.description,
className: 'resources-drawer',
drawerOrder: courseResources._drawerOrder
};
New _drawerOrder to be added to extension schemas (for extensions that populate the drawer):
"_drawerOrder": {
"type": "number",
"required": false,
"title": "Drawer order",
"inputType": "Number",
"default": 0,
"help": "The order in which this extension …

Allow ordering of drawer items (#1393)

---

grunt/tasks/schema-defaults.js

Adding "/" to path to fix #1719 if config.json[build] is defined, as it is by the AT on export.

Fixes #1719

---

src/core/js/libraries/jquery.a11y.js

#1723 
Allow an optional argument to be passed to `$.fn.a11y_text` which when specified will insert and accessible version the given text rather than convert the existing content

Addresses #1723

---

src/core/js/libraries/jquery.a11y.js

Without this addition, calling `.a11y_text(someText)` will only insert the text if accessibility is enabled.
The desired behaviour is to insert the given text regardless, making it accessible if a11y is on.

Additional fix #1723 - still insert text when accessibility is disabled

---

src/core/schema/course.model.schema

Now screen readers will be able to alert the user they got the question wrong in AT-authored courses

Addresses #1732 - add "incorrect" aria label to globals

---

src/core/schema/article.model.schema
src/core/schema/block.model.schema

https://github.com/adaptlearning/adapt_framework/issues/1435

Issue/1435 - Add instruction to article / block schema

---

src/index.html

they're no longer needing as we're not supporting IE8/9 any more

remove conditional comments from index.html

---

src/core/js/drawer.js

The init() function now listens out for adapt:start rather than app:dataReady.

Fixes #1817, resolves race condition in Drawer

---

src/core/js/drawer.js

The init() function now listens out for adapt:start rather than app:dataReady.

Fixes #1817, resolves race condition in Drawer (Patch for 'legacy')

---

grunt/config/copy.js

An issue was introduced in aa1cc4e which passed the core 'libraries' folder through the plugin filter, which would prevent the core libraries copying to the build folder for AT users.

Resolves #1868, reverts Grunt copy of core 'libraries'

---

src/core/js/adapt.js
src/core/js/libraries/jquery.resize.js
src/core/js/models/adaptModel.js
src/core/js/scriptLoader.js

https://github.com/adaptlearning/adapt_framework/issues/1576
Added functions from trickle:
```
Adapt.parseRelativeString(relativeString);
AdaptModel.findRelativeModel(relativeString, { 
filter: function(item, index) { return true; },
loop: false,
limitParentId: null
});
AdaptModel.getAllDescendantModels(isParentFirst);
```
Added jquery behaviour:
```
$(selector).on("resize", callback);
$(selector).off("resize", callback);
$(selector).resize(callback);
```

issue/1576: move trickle jquery.resize library and model functions into core

---

src/core/js/libraries/inview.js

fixes https://github.com/adaptlearning/adapt_framework/issues/1881
fixes https://github.com/adaptlearning/adapt_framework/issues/1873

issue/1873: inview updated to latest

---

src/core/js/libraries/jquery.resize.js

#1884 
To test. 
Before replacing this code should not console log:
```js
$(window).on("resize", function() {
console.log("window resize triggered");
});
$(window).trigger('resize'); // should console log here
$(window).resize(); // won't console log here
```
After replacing it should console log:
```js
$(window).on("resize", function() {
console.log("window resize triggered");
});
$(window).trigger('resize'); // should console log here
$(window).resize(); // should console log here
```

issue/1884: updated jquery.resize to latest bugfix

---

src/core/js/drawer.js
src/core/js/views/drawerView.js

The Drawer wasn't tidying up after itself and left multiple views dangling each time a language was changed while a course was in progress.
This remedies it by triggering a 'drawer:remove' event to remove the drawer completely when 'app:languageChanged' is triggered.

Fixes #1917, adds a 'drawer:remove' event to handle drawer tidy-up

---

src/core/js/libraries/jquery.a11y.js

#1603 
to test:
* check that Jaws can still read text in IE11, test with vanilla project should be fine.

issue/1603: removed jquery.a11y ie8 hack

---

src/core/js/accessibility.js
src/core/js/libraries/jquery.a11y.js
src/core/less/base.less
src/core/templates/drawer.hbs
src/core/templates/navigation.hbs
src/core/templates/notify.hbs
src/core/templates/notifyPush.hbs
src/core/templates/page.hbs

Addresses #1513
(Sorry chris, i completely messed up your original PR when I tried to rebase it with master)
Glossary:
* focusguard - the element which wraps the focus around at the bottom of the page, back to the top
Chris' changes:
* switched focusguard from being moved around to having it exist in the templates (this is backward compatible but will print a deprecated warning)
* switched focusguard event handling from per instance to single global
* extended accessibility helpers so that they output the correct z-index and a11y-ignore class for the active state of accessibility
* added {{focus_wrap}} to templates to make it clear where the focusguard behaviour will appear
* converted aria labels in templates to use {{a11y_aria_label}} helper
* changed scrollEnable + scrollDisable …

use a11y_aria_label/a11y_wrap_focus helpers where applicable #1836

---

src/core/js/notify.js
src/core/js/views/notifyView.js
src/core/templates/notify.hbs

#1892 
#1840 
* handle a pre-instantiated sub view
```js
define([
'core/js/adapt'
], function(Adapt) {
var PopupView = Backbone.View.extend({
initialize: function() {
this.listenToOnce(Adapt, "notify:opened", this.onOpened);
},
onOpened: function(notifyView) {
// notifyView.subView === this
},
remove: function() {
// called when notify is closed
}
});
return PopupView;
});
Adapt.trigger("notify:popup", {
_view: new PopupView({ model: new Backbone.Model({}) })
});
```
* allow sub view to force the notify to resize
```js
Adapt.trigger("notify:resize");
```
* allow sub view to close the notify
```js
Adapt.trigger("notify:close");
```
* allow sub view to cancel the notify (triggers notify:cancelled)
```js
Adapt.trigger("notify:cancel");
```
* provide a hook to sub view to run when popup is …

issue/1892: added notify subview support

---

grunt/config/build-config.js
grunt/helpers.js
grunt/tasks/build-config.js

#1944
This is two separate issues.
1. `getIncludes` was using `require` to fetch JSON rather than a parser
2. `build-config` task wasn't applying the includes filter

issue/1944: fixed build.min.js output and includes bug

---

src/core/js/models/configModel.js
src/core/js/offlineStorage.js

A new event allows plugins to initialise offlineStorage conditionally, by waiting until they're ready.  Previously since Adapt.offlineStorage.ready is defaulted to true, plugins such as the Language Picker would skip any aynchronous offline storage setup.
- Added new 'offlineStorage:prepare' event, which is triggered before 'configModel:dataReady'
- Added Adapt.offlineStorage.hasHandler() function, this indicates if an offlineStorage handler has been setup

Issue 1699 adds better support for non-Spoor based offlineStorage

---

src/core/schema/course.model.schema
src/course/en/course.json

also remove `drawerBack` from course.json as it's not actually used/referenced anywhere
fixes #1991

add closeDrawer to course.model.schema

---

src/core/js/models/configModel.js

The course completion defaults are actually already defined in tracking.js.  It's best to leave them out of the config model defaults.

Resolves #2001, corrects issue with configModel defaults

---

src/core/js/libraries/jquery.a11y.js
src/core/less/base.less

#1998 
* removed ios9 focus correction from user input controls (text or select)
* removed ios9 focus correction for interacting with `:before` and `:after` elements
* removed restrictions on focus outline as the rest of the code doesn't apply the same restrictions
* removed redundant ie8 class selector for focused elements (ie8 didn't have the `:focus` selector and had a legacy fix to add a `.focused` class, which has since been removed)

issue/1998: remove buggy ios fixes

---

src/core/js/models/itemsComponentModel.js

#2035 
Bug fix for error when no active item exists and setActiveItem is called.

issue/#2035: bug in setActiveItem when no item active

---

src/core/js/adapt.js

Fixes #2041.
I haven't done anything about the following, but happy to update this PR if there's interest:
> I also wonder whether this should throw an error, as this breaks the app completely. It may be useful to just log a warning, and throw an error at the point we attempt to render the component?

 Log component name on Adapt.register error

---

grunt/tasks/help.js
grunt/tasks/translate.js

grunt help shows not all tasks from "grunt/tasks/translate.js". It takes only first task from there (**translate:export**). See below:
```
$ grunt help
Running "help" task
Adapt Learning automated build process
See below for the list of available tasks:
build               Creates a production-ready build of the course
*
*    
translate:export    Export Course Data into Language files ready to be translated
Run a task using: grunt [task name]
For more information, see https://github.com/adaptlearning/adapt_framework/wiki
```
Now it displays both tasks:
```
$ grunt help
Running "help" task
Adapt Learning automated build process
See below for the list of available tasks:
build               Creates a production-ready build of the course  
*
* …
```

Show multiple tasks from grunt/tasks/task-file.js in "grunt help"

---

src/core/js/models/itemsComponentModel.js

#2071 
Switched to `_children` from `_items`.

fixes issue/#2071 : itemsComponentModel switched to _children

---

src/core/js/libraries/jquery.a11y.js
src/core/js/popupManager.js
src/core/js/views/drawerView.js

#2107 
* Allow `drawer:closeDrawer` to have a specified focus to element
* Moved some behaviour from `$.a11y_popdown()` to Adapt popup manager to facilitate correct focusing

accessibility: issue/#2107 allow defined focus from drawer close

---

grunt/tasks/scripts.js

Without the full path to the JS this was causing an error.

Fixes #2212 - prepends the current working directory to the script path

---

src/core/js/views/drawerView.js

Same as the `legacy` fix: https://github.com/adaptlearning/adapt_framework/pull/2211.
This time for the `master` branch.
```
Setting this._isCustomViewVisible = false; after that creates this UX:
- A user can click toggleDrawer it will open and it will show the drawerItems
- A user can click progressBar when drawer is open and it will show progressBar stats in the drawer
- A user can then click toggleDrawer again and it will show the drawerItems again
- A further click on toggleDrawer will hide the drawer
This should be in keeping with the link adaptlearning/adapt_framework#218 @tomgreenfield mentioned but also hiding the drawer using the toggleBtn
```

Fix toggleBtn not closing the drawer when only 1 drawer item

---

src/core/js/models/adaptModel.js

#2180 
* Stop findDescendantModels descending into models with no defined _children type - itemsComponentModel specifically at the moment.

issue/#2180 Return if no defined _children type

---

src/core/js/libraries/jquery.a11y.js

#2094
* Siblings of the parent branch of the popup tag become `aria-hidden=true tabindex="-1"`
* Tab index original values are better restored by accounting for no tab index rather than defaulting to `0`
Using JAWS, enable accessibility mode, open the drawer or a notify. Use the up and down arrow keys to navigation around. You should not be able to read any content behind the popup.

accessibility: issue/#2094 popups

---

grunt/tasks/schema-defaults.js

Make sure course.json is written to the output folder and not source folder on create-json-config task.
#2224

Fixed issue #2224

---

src/core/js/views/drawerView.js

Setting this._isCustomViewVisible = false; after that creates this UX:
A user can click toggleDrawer it will open and it will show the drawerItems
A user can click progressBar when drawer is open and it will show progressBar stats in the drawer
A user can then click toggleDrawer again and it will show the drawerItems again
A further click on toggleDrawer will hide the drawer
This should be in keeping with the link adaptlearning/adapt_framework#218 @tomgreenfield mentioned but also hiding the drawer using the toggleBtn
This was originally here: https://github.com/adaptlearning/adapt_framework/pull/2211
Not sure what happened or why it was closed (or if it was me who closed it) but regardless here is the new one.

Issue/2209-legacy - Fix toggleBtn not closing the drawer when only 1 drawer item

---

src/core/js/adapt.js
src/core/js/models/routerModel.js
src/core/js/router.js

#2233 
Added behaviour to allow the body to become focused once adapt navigates.
This causes screen readers to notify the user of changed page content.

accessibility: fixes #2233 Navigation refocuses on body

---

src/core/js/libraries/jquery.a11y.js

#2231 
Force click events on focusable elements to assign focus. Useful for screen readers to maintain placement on returning from popups.
#2232 
Stop click causing focus on non-focusable elements.

accessibility: fixes 2232 2231 Cause click events to focus

---

src/core/js/libraries/jquery.a11y.js

N.B. this check was accidentally removed by https://github.com/adaptlearning/adapt_framework/commit/c76e1a2d79a7fc0e09cb5173652c4a5be67e1161

Fix for issue #2228

---

src/core/js/libraries/inview.js

#1873 
* Update to inview to read computed styles

Fix for issue/1873

---

src/core/less/base.less

#2179 
* Remove focusguard from document flow whilst retaining top position to remove the whitespace height but keep the element in position
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206

accessibility: issue/2179 Remove focusguard from box flow

---

src/core/js/libraries/jquery.a11y.js

#2080 
* Fixed bug in findForward
* When an element loses focus due to the addition of the [disabled] attribute, it will now force a focus forward instead of falling backward.

accessibility: issue/2080 Fixed bug, forced [disabled] focus loss to focus forward

---

grunt/config/replace.js

In our theme, we want to add some course data into meta tags, etc, in a custom `required/index.html` file. 
Currently, in `required`, the XML files are processed so you can do things like this from https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/imsmanifest.xml#L9
```
<langstring xml:lang="x-none"><![CDATA[@@course.title]]></langstring>
```
if we add `*.html` to the grunt replace job as well as `*.xml`, we should be able to do the same thing in index.html, meaning that themes can then automatically pull in data from the course. For instance:
```
<title><![CDATA[@@course.title]]></title>
```
This is my first venture into the internals of the Adapt framework, so if there is a way I should be testing these jobs, or otherwise improving my PR, please tell me!

Add ability to insert variables into HTML files

---

src/core/less/base.less

#2308
* Remove unnecessary styling on the wrapper and navigation
* Moved responsive widths to max-widths
Please check if this is breaking for your current themes.
Please test with vanilla pr [#228](https://github.com/adaptlearning/adapt-contrib-vanilla/pull/228)
Test source:
[2308.zip](https://github.com/adaptlearning/adapt_framework/files/2698757/2308.zip)

issue/2308: fixed base responsive-layout styling

---

src/core/js/libraries/jquery.a11y.js

#2304 
* Forces focus from trickle button to land directly on the heading rather than on the heading children. This solves the misreading in JAWS

accessibility issue/2304 role="heading" isReadable

---

src/core/schema/config.model.schema

Apologies, missed a tiny but crucial amend, [already merged into framework 4](https://github.com/adaptlearning/adapt_framework/commit/0e8bed46c38624cb2dc70e70e76f42536427e44d#diff-0909d803337ea772187699d7c7729838), that fixes the authoring tool's _Configuration settings_ page.
Part of #2306.

Fix _disableAnimationFor (framework 3)

---

grunt/config/replace.js

This ensures 'adapt_scorm' will be used as a default if the corresponding property is missing.

Resolves #2247, adds a shim to support custom manifest 'identifier'

---

src/core/js/helpers.js

#2339 
* When no component globals are included the container object isn't created. This happens when only using a text/graphic component in a course.

issue/2339: Fixed helper expecting missing object

---

grunt/config/replace.js

This commit supports a corresponding change in Spoor by providing backwards
compatibility for JSONs which may be missing the 'manifiest_identifier' attribute.

Resolves #2247, adds a shim to preserve adapt_manifest identifier

---

src/core/js/logging.js
src/core/js/scrolling.js
src/core/js/tracking.js

The tracking, logging and scrolling modules were only checking the Adapt.config object so once it's loaded they are ok to continue.

Resolves #2386, switches listeners out for 'configModel:dataLoaded'

---

src/core/schema/course.model.schema

Fixes #2345. Duplicate of #2346.
:skull: Need to discuss exactly when this should be merged, as it will break authoring tools older than v0.7.0 due to the new `Users` input type.

Update sharing options (legacy)

---

src/core/schema/course.model.schema

Fixes #2345.
:skull: Need to discuss exactly when this should be merged, as it will break authoring tools older than v0.7.0 due to the new `Users` input type.

Update sharing options

---

src/core/js/models/itemsQuestionModel.js

#2415 
* Stopped `QuestionModel.extend` from modifying `ItemsComponentModel.prototype.constructor` which was causing `QuestionModel` to appear in the inheritance chain of `ItemsComponentModel`. The process of blending `QuestionModel` and `ItemsComponentModel` now takes only the own properties from `ItemsComponentModel.prototype`, minus the `constructor` function and brings them into a blended class first.
(The `constructor` function is assigned by Backbone as an enumerable property as part of the `.extend` process.)

issue/2415: Fix ItemsComponentModel inheritance chain

---

src/core/js/adapt.js
src/core/js/views/adaptView.js
src/core/less/base.less

#2395
* Capture child views
* Provide findViewByModelId api
#2389
* Remove rtl prepend

Resolves #2395 and #2389 - Capture child views

---

src/core/js/wait.js

To prevent an unhandled expection or a call to begin() not having a corresponding end() from blocking rendering of the Adapt content, a 7-second timeout is now added on every begin.  If the time has elapsed since the last begin() the outstanding calls to Adapt.wait.end() will be triggered.
Also added a _.once() call to the for() callback and replaced double quote marks in strings with single quotes.

Resolves #2439, adds a timeout to Adapt.wait

---

src/core/js/libraries/jquery.a11y.js

else IE11 won't actually remove it - fixes #2466
also remove 'mousewheel' as it's deprecated and all browsers now have support for 'wheel'

pass all three arguments when calling removeEventListener

---

src/core/js/models/itemsComponentModel.js

If '_items' was not set this would throw an error which would prevent the content from loading.

Resolves #2480, adds a guard on '_items' property

---

src/core/js/a11y.js

#2534 
* Allow normalize and removeBreaks to accept only non-null strings, as helpers tend to re-route handlebars context object

issue/2534 allow only non-null strings into removeBreaks and normalize

---

src/course/config.json

to match the default value in a11y.js (see #2530)

config.json: change _isFocusOutlineKeyboardOnlyEnabled to true

---

src/core/js/models/adaptModel.js

#2563 
* findRelativeModel finds in the next parent on descendent type searches instead of finding in parent
This is an issue when using trickle on article with @block +1

issue/2563 fixed findRelativeModel for descendent searches

---

src/core/js/models/adaptModel.js

#2563 
* findRelativeModel finds in the next parent on descendent type searches instead of finding in parent
This is an issue when using trickle on article with @block +1

issue/2563 fixed findRelativeModel for dependents

---

src/core/js/a11y.js

by adding `function` keyword
fixes #2570

correct accidental use of ES6 'Shorthand method definition'

---

src/core/required/index.html

it hasn't prevented pinch-zooming on iOS since v10

amend viewport meta tag

---

src/core/js/views/componentView.js

Fixes https://github.com/adaptlearning/adapt_framework/issues/2595
Updated selector to match v5 naming convention in `setupInviewCompletion` function for when a plugin uses the default.

Updated inview selector

---

src/course/en/components.json

enable `toggleCaptionsButtonWhenOnlyOne` as the most typical use-case is only to have one captions language
use native controls on tablet/smartphone to prevent double-display of captions/controls (#2477)
better for a11y to have controls always on-screen

better media component config for captions, a11y

---

src/core/libraries/imageReady.js

#2625 
* Prevented issue where no 'currentStyle' property exists on SVGs

issue/2625 Fix for ie11 svg

---

src/core/js/models/adaptModel.js
src/core/js/models/itemsComponentModel.js

#2649
* Added `change_isActive` event bubbling from `ItemsComponentModels`
Allows:
```js
Adapt.course.on("bubble:change:_isActive", function(event) {
// event.type == "change:_isActive
// event.target == originating model
// event.value === boolean
// event.deepPath === array of models traversed
});
```

issue/2649 added change:_isActive event bubbling

---

grunt/config/babel.js
grunt/config/watch.js
grunt/tasks/build.js
grunt/tasks/dev.js
grunt/tasks/diff.js
grunt/tasks/language-data-manifests.js
grunt/tasks/server-build.js
src/core/js/collections/adaptCollection.js
src/core/js/collections/adaptSubsetCollection.js
src/core/js/data.js
src/core/js/models/buildModel.js
src/core/js/models/courseModel.js
src/core/js/mpabc.js

fixes #2645 
PR goes into #2714 then into #2713 then into #2711 then into master
* Adapt is now JSON filename agnostic in the language folder (`build.js` and `config.json` are still fixed filenames outside of the language folders). 
* Each file must contain an object or an array of objects with, at minimum a `{ "_type": "" }`, `{ "_component": "" }` or `{ "_model": "" }` attribute on each JSON file object as this denotes the corresponding model inside the framework.
* Each language folder must have a `{ "_type": "course" }` object.
* grunt task `language-data-manifests`
* Reworked `src/core/js/data.js` to load manifest, files and become the collection for all models. It now has no references to the menu, page, article, block and component structure
* Moved menu, page, article, block and …

issue/2645 Added manifest creation and loading

---

grunt/helpers/Schemas.js
grunt/helpers/schema/GlobalsSchema.js
grunt/helpers/schema/Schema.js

fixes #2721 
* Component model schema names were not captured correctly
* Added plugin origin to schemas to aid debugging.

issue/2721 Fixed component schema naming

---

src/core/js/app.js
src/core/js/fixes.js
src/core/js/fixes/img.lazyload.js
src/core/js/templateRenderEvent.js
src/core/js/templates.js
src/core/js/views/navigationView.js
src/core/libraries/imageReady.js
src/core/schema/config.model.schema
src/course/config.json

#2734
All template and partial `img` tags will now have the `loading="eager"` added by default unless the tag already contains a `loading` attribute. `imageready` will now ignore `loading="lazy"` `img` tags.
* Introduced `template:preRender`, `template:postRender`, `partial:preRender` and `partial:postRender` events to Adapt
* Sub folder `core/js/fixes` for essential fixes
* `img.lazyload` fix, to inject `loading="eager"` attribute into `img` tags if `loading` attribute is missing
* Added `_fixes` object to config.json
* Added `_fixes._imgLazyLoad: true` to config.json to control image lazy load fix, defaults to true
* `imageready` `background-image` loader to ensure the `loading="eager"` attribute is applied
* `imageready` skips loading checks on explicitly `loading="lazy"` images

Added template + partial render events and a fix for lazyloading images

---

src/core/js/models/componentModel.js

#2787 
* Registered `ComponentModel` for backward compatibility for view-only components

issue/2787 Fixed backwards compatibility for view-only components

---

src/course/en/articles.json
src/course/en/blocks.json

first trickle button now reads 'Continue' (instead of 'Begin'); last one now reads 'Show results'.
fixes #2803

default course: assessment trickle button label improvements

---

src/core/js/a11y/scroll.js

#2800 
* Allows two finger gestures to pass through scroll blocking on touch, re-enabling zoom

issue/2800 Enabled zoom on fixed position popup elements with scroll disabled

---

grunt/helpers.js

#2836 
To remove a plugin on `grunt build` use:
```json
"build": {
"productionExcludes": [
"adapt-devtools"
]
},
```
* `Adapt.build.get('type') === 'production' || 'development';`
* config.json:`build.productionExcludes`

issue/2836 Added ability to exclude plugin(s) from 'production' build

---

src/core/js/models/itemsQuestionModel.js
src/core/js/models/questionModel.js
src/core/js/views/buttonsView.js
src/core/js/views/questionView.js

#2812 
* `questionView:showInstructionError` event to allow for instruction error popups
* `_canSubmit` with locking to allow extension to lock `_canSubmit` to true
* Old instruction error behaviour
Use extension [adapt-contrib-instructionError](https://github.com/adaptlearning/adapt-contrib-instructionError) as discussed for warnings on invalid submissions.
Requires prs in matching and textinput to disable submit button in both cases [matching#125](https://github.com/adaptlearning/adapt-contrib-matching/pull/125), [textinput#101](https://github.com/adaptlearning/adapt-contrib-textInput/pull/101)

issue/2812-1 Disabled submit button by default, facilitate instruction error

---

src/core/js/views/drawerView.js

See #2851 
* Added handler for external remove events fired when the drawer is open (originating from url changes, custom extensions etc)

issue/2851 Fixed DrawerView passing Backbone view to Adapt.a11y.focusFirst

---

src/core/js/models/questionModel.js
src/core/js/scrolling.js
src/core/js/views/questionView.js

#2812 
* Multiple attempt resets now check `canSubmit`
* Bad merge order for cloned model `_canSubmit` locking
original [issue](https://github.com/adaptlearning/adapt-contrib-matching/pull/125#pullrequestreview-454012732)

issue/2843 Fixed submit disabled on reset click

---

src/core/js/models/componentModel.js
src/core/js/models/itemsComponentModel.js
src/core/js/models/questionModel.js

#2845 
Presentation components hotgraphic and accordion will keep visited states (narrative will also but there is no visible representation of visited states in narrative).
This should all carry on working as before except some crucial `QuestionModel` only behaviour is now also accessible to `ComponentModel` and by extension `ItemsComponentModel`. 
* Moved` _attemptStates` API from `QuestionModel` to `ComponentModel`
* Moved `_userAnswer` API from `QuestionModel` to `ComponentModel`
* `ItemsComponentModel` save and restore behaviour
* `ComponentModel._userAnswer` reset behaviour
Test with spoor [pr#197](https://github.com/adaptlearning/adapt-contrib-spoor/pull/197) or using spoor branch [issue/2805](https://github.com/adaptlearning/adapt-contrib-spoor/tree/issue/2805)
Use …

issue/2845 Presentation component save+restore

---

src/core/js/notify.js
src/core/js/views/notifyView.js
src/core/less/core/notify.less

#2847 
* Notify can now render any Adapt `_id` as a subview
* `Adapt.notify.stack` for a list of open popups
* Resize jumping
* Use native `Adapt.log.deprecated ` instead of a notify specific one
* Converted to ES6 classes
* Notifies get appended to the body rather than prepended, preserving their stack order
* Added styling so that shadow layers appear in the correct order and above the navigation bar
* Only the last notify will respond to the last close / cancel event
This should be accessibility tested. The feedback notify in the mcq should appear over the mcq notify and be completely keyboard navigable.
To show an mcq:
```js
var Adapt = require('core/js/adapt');
Adapt.notify.popup({
_id: 'c-65'
});
```
To show a media component:
```js
var Adapt = require('core/js/adapt'); …
```

issue/2847 Improved notify subview handling

---

grunt/helpers/Translate.js
grunt/tasks/translate.js

#2853 
`translate:import` delimiter detection was broken when the first value to import contained slashes (html usually).
```csv
"articles/a-05/title/","<div>a-05</div>"
"articles/a-10/title/","a-10"
"articles/a-15/title/","a-15"
"articles/a-15/_trickle/_button/startText/","Continue"
"articles/a-20/title/","a-20"
```
* Now detects delimiters only when none is specified at the command line `--csvDelimiter=','`
* Now only supports the detection of the delimiters , ; | tab and space
* Will now error if csv delimiter isn't specified and cannot be detected
* Still exports with comma as the default delimiter
[Regexp](https://github.com/adaptlearning/adapt_framework/pull/2857/files#diff-f99b28ae92e4435fff8d5fd848f99463R298) test: [/^[^,;\t| \n\r]+\/"{0,1}[,;\t| …

issue/2853 Fixed csv delimiter detection on translate import

---

src/core/js/a11y.js

#2886 
Firefox misreports `$(window).scrollTop()` frequently, returning 0 in unusual circumstances. The `preventScroll` fix for `Element.focus` - for browsers which don't support the `preventScroll` option, ie11 and safari at the time of writing - is necessary but should not be applied to Firefox where it often causes the scroll to bounce back to 0.
* Stopped `preventScroll` fix applying in Firefox
References:
Browser compatibility - https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus#Browser_compatibility
Safari support ticket for preventDefault - https://bugs.webkit.org/show_bug.cgi?id=178583
Notes:
Have yet to identify why Firefox misreports the `$(window).scrollTop()`, it reads fine in the debugger console or watch window. The bug seems to appear at frequency …

issue/2886 preventScroll fix now excludes firefox

---

src/core/js/scrolling.js
src/core/js/views/contentObjectView.js

#2901 
* Defensive code to prevent `contentObjectView.renderTo(id)` from attempting to render to itself
* Typo in `Adapt.scrollTo`

issue/2901 Fix to prevent error in contentObjectView.renderTo

---

src/core/js/data.js

should only be calling `getStartHash` if start page is enabled, not the other way round
fixes #2907

fix bug in triggerDataReady

---

src/core/js/views/adaptView.js

#2903 
* `event` object life-cycle event `closed`

issue/2903 Close the event life-cycle on requestChild no model

---

src/core/less/_defaults/base.less

Resolves https://github.com/adaptlearning/adapt_framework/issues/2916
* Added media query to target ie11 and force `<img>` with an `.svg` src to 100% width

ie11 .svg in <img> fix

---

src/core/less/core/global.less

Related issue https://github.com/adaptlearning/adapt_framework/issues/2912
* Add fix for Firefox container height misalignment
* Moved *-title-inner CSS from Vanilla theme to Core

Added fix for firefox outline container misalignment

---

src/core/js/adapt.js
src/core/js/router.js
src/core/js/scrolling.js

#2928 
* Sub-contentobject urls are now compatible with the browser back and next buttons, `#/id/c-80`, `#/id/c-35`, `#/id/c-25` etc
* `Adapt.navigateToElement` with any selector `.c-25 .component__instruction`, the first part is assumed to be the `id`
* `Adapt.navigateToElement` will now handle being passed an `id` or a selector
* `Adapt.scrollTo` and `Adapt.scrolling.scrollTo` and incorporated the scrolling behaviour properly into `Adapt.router.navigateToElement`

issue/2928 Fixes navigateToElement, deprecates scrollTo

---

src/core/js/views/adaptView.js

Resolves https://github.com/adaptlearning/adapt_framework/issues/2938
* Stop listening to the event listeners in the remove function

Added stop listener to remove function

---

src/core/js/wait.js

issue/2743 - remove the flush for Adapt.wait

---

src/course/en/components.json

Dependent on https://github.com/adaptlearning/adapt_framework/issues/2936
* Adds two new configuration options, `_isNarrativeOnMobile` and `_useNumberedPins`, to the Hotgraphic component in the example course.

Add new hotgraphic config to example course

---

src/core/schema/config.model.schema

Resolves https://github.com/adaptlearning/adapt_framework/issues/2952
* Removes `_isTextProcessorEnabled` property from config.model.schema

Removed _isTextProcessorEnabled

---

grunt/config/connect.js

Reference: https://github.com/gruntjs/grunt-contrib-connect/issues/254.
Resolves #2954.

Convert port string to number

---

src/core/js/a11y.js
src/core/js/a11y/browserFocus.js
src/core/js/views/buttonsView.js
src/core/templates/buttons.hbs

resolves #2950 
* Made submit and feedback button available to the screen reader when disabled by switching from `disabled="disabled"` to `aria-disabled="true" tabindex="-1"`. The screen reader instead of reading nothing now reads "disabled button" or "dimmed button".
Reference:
https://a11y-101.com/development/aria-disabled

issue/2950 Switch from disabled to aria-disabled for ButtonsView

---

grunt/tasks/javascript.js
package.json

* Updated [babel-plugin-transform-amd-to-es6](https://github.com/cgkineo/babel-plugin-transform-amd-to-es6) to the latest version ([relevant amend](https://github.com/cgkineo/babel-plugin-transform-amd-to-es6/commit/9bb4bde94fc73041781ca3e423c47fb2445be64f))
* Added configuration option to ignore nested requires

fixes #2997 CommonJS and nested requires

---

grunt/tasks/compress.js
package.json

#3002 
* Made imagemin dependencies optional
* Added error when `grunt compress` is executed without requisite dependencies
1. Remove `node_modules/imagemin`
2. Run `grunt compress`
1. [Optional dependencies](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#optionaldependencies)

issue/3002 Made imagemin dependencies optional

---

grunt/helpers.js
grunt/tasks/javascript.js
src/course/config.json

fixes #3017 
* `config.json:build.strictMode` to turn on strict mode directives in javascript output
* Turned on in standard course

issue/3017 Added config.json:build.strictMode

---

src/core/js/a11y.js

resolves #3022 
* Moved force focus code outside of the preventScroll block
Paste this in the console to see the `document.activeElement` changes
```js
var ae = document.activeElement;
setInterval(function() {
var ae2 = document.activeElement;
if (ae2 === ae) return;
ae = ae2;
console.log(ae);
}, 100);
```

issue/3022 Force focus fix

---

src/core/js/adapt.js
src/core/js/data.js
src/core/js/models/adaptModel.js

fixes #2805 
Provides a simple method of identifying models based upon the course's `_trackingId` properties, regardless of their location, be them on the `blocks` or `components`.
* `Adapt.findByTrackingPosition` similar to `Adapt.findById` but for `_trackingId` relative save/restore functions
* `AdaptModel.trackingPosition` which returns the model's trackingPosition relative to its nearest `_trackingId`
A tracking position is comprised of two numbers, the `_trackingId` and the relative offset from it. The relative offset is positive for a descendant or negative for an ancestor.
* Comment in `Adapt.findById` was inaccurate
```js
// Test all trackingPositions can be found for the course
Adapt.data.forEach((model) => {
var id = model.get('_id');
var trackingPosition = …
```

issue/2805 Added a mechanism for trackingId location agnosticism

---

src/core/js/a11y/browserFocus.js

fixes #3064 
* Explicitly convert jquery objects to array before spreading

issue/3064 Cannot spread non-iterable jquery object in ie11

---

src/core/less/core/nav.less
src/core/templates/nav.hbs

Resolves https://github.com/adaptlearning/adapt_framework/issues/3040
* Shows 'skip navigation' button on browser tab focus 
Note: skip navigation button does not appear when focused using the arrows keys in combination with a screen reader

skip nav btn visible when focused

---

src/core/js/models/itemsQuestionModel.js
src/core/js/views/buttonsView.js
src/core/templates/buttons.hbs

part of #2942
~~Note: will also require updates to all the core question components, these will follow shortly~~ Now done - except for textInput
~~I'll also try and add a demo build so that anyone wanting to actually test this out can do so~~ done, see [this comment](#issuecomment-790584389)

allow correct answer/hide correct answer buttons to be keyboard/screen reader accessible

---

grunt/tasks/tracking-remove.js

allow the tracking-remove grunt task to run even if spoor isn't installed

---

src/core/js/a11y/browserFocus.js

search element's parents for aria-disabled

---

src/core/js/a11y.js

fixes #3101 
* a11y api now starts up at `configModel:dataLoaded` instead of `app:dataLoaded`

issue/3101 a11y startup at configModel:dataLoaded

---

src/core/js/data.js
src/core/js/models/configModel.js

Work arising from suggestion on https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/46

Language set from param

---

grunt/helpers/Translate.js

fixes #3126
* Changed `translate:import` to read json files as json
* JSON format always tried to set an initial nested object because of an extra, unremoved path slash `"/"`

issue/3126 Bugfix: read json not string buffer

---

src/core/js/views/headingView.js

fixes #3132 
* Header view now performs a non-destructive rerender

issue/3132 Non-destructive header rerender

---

src/core/templates/partials/component.hbs

part of https://github.com/adaptlearning/adapt_framework/issues/3142
* `id` to `component__header`
Use prs [gmcq#129](https://github.com/adaptlearning/adapt-contrib-gmcq/pull/129) and [mcq#159](https://github.com/adaptlearning/adapt-contrib-mcq/pull/159), then <kbd>Tab</kbd> to navigate to mcq/gmcq answer options.
The answer option reads the entire component header, better orientating the user.

issue/3142 Added id to component__header

---

src/core/js/models/itemsQuestionModel.js

#3148
Added support for selecting any correct answer.
Added support for marking as partly correct if any `_isPartlyCorrect` item is selected.
* `_isPartlyCorrect` to question items
* `isCorrect` is `true` when a `_selectable` number of `_shouldBeSelected: true` items are active
* `isCorrect` is `false` if any `_isPartlyCorrect: true` items are active
* `isPartlyCorrect` is `true` if any `_isPartlyCorrect: true` items are active
To test in the AAT use https://github.com/adaptlearning/adapt-contrib-mcq/pull/160 and https://github.com/adaptlearning/adapt-contrib-gmcq/pull/130

issue/3148 Added partly correct and any correct answer options to ItemsQuestionModel

---

src/core/js/adapt.js

fixes #1568 
* Allowed `Adapt.parseRelativeString` to return `{ type: 'menu', offset: 0 }` when receiving type groups without an offset like `@menu`, `@page`, `@article` rather than `@menu+0` which is how to find the current ancestor menu

issue/1568 Allow parse of @menu @page @article without offsets

---

src/core/js/models/itemModel.js
src/core/js/models/itemsQuestionModel.js
src/core/js/models/questionModel.js
src/core/js/views/questionView.js

#3163 
fixes #1974
fixes #893
* `QuestionModel.score` returns `0` for incorrect/partly correct or `maxScore` for correct
* `QuestionModel.maxScore` returns `_questionWeight`
* `QuestionModel.minScore` returns `0`
* `QuestionModel._hasItemScoring` to control item scoring
* `QuestionModel.updateRawScore()` adds `_rawScore = get score`, `_maxScore = get maxScore`, `_minScore = get minScore` on `init` and `markQuestion` to give access to the values in templates
* `ItemsQuestionModel.score` when `_hasItemScoring === true` return sum of `_items._isActive && _items._score`
* `ItemsQuestionModel.maxScore` when `_hasItemScoring=== true` return the sum of `_selectable` highest positive `_items._score`
* `ItemsQuestionModel.minScore` when `_hasItemScoring=== true` return the sum of `_selectable` …

issue/3163 New scoring api

---

src/core/js/models/adaptModel.js

fixes #1486 
* Ignore optional source models in locking derivation, such that optional models can be locked by mandatory models but no model can be locked by optional models. [Bottom part](https://github.com/adaptlearning/adapt_framework/pull/3146/files#diff-260f88149840d5e54230b6e03f9b641d71aef375dcb74cefffd553798f94412aR719-R761)
* Some linting issues. [Top part](https://github.com/adaptlearning/adapt_framework/pull/3146/files#diff-260f88149840d5e54230b6e03f9b641d71aef375dcb74cefffd553798f94412aR19-R694)

issue/1486 Ignore optional source models in locking

---

package.json

fixes #3180 
* [babel-plugin-transform-amd-to-es6](https://github.com/cgkineo/babel-plugin-transform-amd-to-es6) node module to latest version, which has a new umd > amd preconversion then amd > es6
* Add [adapt-chartjs](https://github.com/dancgray/adapt-chartjs) to your project, the umd library `js/Chart.min` should transpile correctly

issue/3180 Update babel-plugin-transform-amd-to-es6

---

src/core/js/views/questionView.js

fixes https://github.com/adaptlearning/adapt_framework/issues/3195
* Typo with missing `this.model` in compatibility layer

issue/3195 Missing .model on line 465 creating error

---

grunt/config/javascript.js
grunt/tasks/javascript.js
package-lock.json
package.json

#3208 
* Remap `../libraries/` or `core/js/libraries/` style imports to `libraries/` which will keep them out of the compilation process
* `babel-plugin-transform-amd-to-es6` from v 0.5.4 to 0.6.1

issue/3208 Correct bad libraries/ imports

---

gitmodules.js

fixes #3232 
Fixes `adapt create course` for `src/core` to [adapt-contrib-core](https://github.com/adaptlearning/adapt-contrib-core) submodule.
* If the `preinstall` script is run from a zip download rather than a clone, ensure submodules are cloned instead of being updated.
Run `$ adapt create course` with branch `issue/3232` instead of `master`

issue/3232 Fix for adapt-cli and adapt-contrib-core

---

.browserslistrc
grunt/tasks/javascript.js

part fix for #3236 
* Allow ES output to be determined by external config file as per https://babeljs.io/docs/en/babel-preset-env#browserslist-integration
* Ensure to switch to [issue/3236](https://github.com/adaptlearning/adapt-contrib-core/tree/issue/3236) branch of adapt-contrib-core [pr#1](https://github.com/adaptlearning/adapt-contrib-core/pull/1) remove `ie11` line from [.browserslistrc](https://github.com/adaptlearning/adapt_framework/blob/f46f558ce3b4d03f54751ee0d115947725047e83/.browserslistrc#L9) and `grunt dev`

issue/3236 Allow for drop of ie11

---

gitmodules.js

fixes #3240 
* `npm install` now uses `git clone` rather than `git submodules` in order to support tag names

issue/3240 Removed submodule cloning for standard clones

---

.gitmodules
gitmodules.js

fixes #3252 
* Ensured path is correct for git commands
* Moved install branch to non-conflicting property in `.gitmodules`
* Remove potentially errorneous files before attempting to clone

issue/3252 Extra path and error handling to gitmodules

---

gitmodules.js

fixes #3259 
* Fixed npm preinstall prune error

issue/3259 Fixed unnecessary prune in gitmodules

---

grunt/helpers.js

fixes #3256 
* Improved dev mode identifcation for `Adapt.build` and `window.ADAPT_BUILD_TYPE` https://github.com/adaptlearning/adapt-contrib-core/blob/9778757daec05a1af2942c676558b146e83ea38c/required/index.html#L5

issue/3256 Better dev mode identification for client side

---

grunt/config/replace.js

fixes bug in https://github.com/adaptlearning/adapt_framework/pull/3278
fixes #3277 
* Strip null values from `build` object in `replace` task for `imsmanifest.xml`

issue/3277 Fix for build.cachepath = null

---

README.md
package.json

Fixes #3288
The grunt tasks of the framework now require Node v14+ but this was not indicated in the documentation

Highlight the Node requirements of the framework

---

src/course/en/articles.json

fixes #3287 
* Populated vanilla course assessment article with relevant example.json defaults

issue/3287 Added missing assessment configurations

---

.browserslistrc

fixes #3309 
Reduces the size of the output by some 300kb, improves the relationship between the source-code and source-maps thereby improving in-browser debugging, speeds up compile.
* IE11 compilation

issue/3309 Drop IE11 compilation

---

grunt/config/copy.js
grunt/config/json-minify.js
grunt/config/jsonlint.js
grunt/config/less.js
grunt/config/watch.js
grunt/helpers.js
grunt/helpers/Data.js
grunt/helpers/Framework.js
grunt/helpers/Plugins.js
grunt/helpers/Translate.js

part of https://github.com/adaptlearning/adapt_framework/issues/3305
* Allow alternative course folder name to be specified at the grunt command `grunt dev --coursedir=alternative` or in the adapt.json at `"coursedir": "alternative"`
1. To change the folder from `course` to `alternative` and test out the code
```sh
git clone https://github.com/adaptlearning/adapt_framework 3305-course
cd 3305-course
git checkout issue/3305
mv src/course src/alternative
adapt devinstall && npm install
cd src/core
git checkout issue/3305
cd ../../
grunt dev --coursedir=alternative
```
2. You will need to find and replace all of the images in the json files from `course/` to `alternative/`

issue/3305 Support for alternative course folder name

---

grunt/helpers.js
grunt/tasks/javascript.js

fixes #3312 
* `targets` to config.json:build
`"targets": "ie 11, last 2 chrome versions, last 2 firefox versions, last 2 safari versions, last 2 edge versions, last 2 ios_saf versions, last 2 and_chr versions, firefox esr"`

issue/3312 Allow configurable javascript targets

---

grunt/tasks/javascript.js

fixes #3329
* Added `.browserslistrc` defaults such that the framework can compile without the file

Fix: Added browserslistrc defaults (fixes #3329)

---

src/course/en/components.json

https://github.com/adaptlearning/adapt_framework/compare/issue/3336
fixes https://github.com/adaptlearning/adapt-contrib-media/issues/235
- Closed Captions default to OFF if srclang is not english

Closed Captions default to OFF if srclang is not english (Fixes #3336)

---

.github/workflows/releases.yml

Fixes #3340 
* Packages used for release action updated to Node16 compatible version

Update: release job now uses v3 for checkout and setup-node actions

---

grunt/tasks/build.js
grunt/tasks/dev.js
grunt/tasks/diff.js
grunt/tasks/server-build.js

Fixes #3342
* Added an additional script for plugins to hook into. Fires following the files being copied to the build folder, but before other helper commands such as `replace`.

New: Added grunt `scripts:adaptpostcopy` command

---

src/course/en/components.json

* Adds ariaQuestion field to all question components in default JSON.
* Fixes #3353 
1. Install PR
2. Ensure latest fixes to question components are added
3. Adjust ariaQuestion field and listen to output via screen reader
[//]: # (Mention any other dependencies)
Testing is dependent on the successful approval of the following issues:
https://github.com/adaptlearning/adapt-contrib-mcq/issues/190 …

Fix: Adds ariaQuestion field to JSON default settings (fixes: 3353)

---

grunt/config/less.js

fixes #3361 
* Reverted to generic globs so that, whether or not --menu or --theme are defined at the terminal, the globs work properly

Fix: Revert to generic less globs for theme and menu (fixes #3361)

---

grunt/helpers/CacheManager.js
grunt/tasks/javascript.js

fixes #3363 
* Allow adapt_framework to store javascript compilation cache files in the operating system temp folder, cleaning up files, once a day, if they are older than a week. Reduces subsequent compilation times sustantially. Initial compilation remains unchanged. Files are cached in `$TMPDIR/adapt_framework/`.

New: Cache management for subsequent compilation improvements (fixes #3363)

---

grunt/tasks/scripts.js

fixes #3365 
* Add `coursedir` (and all other compliation variables) in script `options` arguments

Fix: Pass cli variables into scripts (fixes #3365)

---

grunt/helpers/Framework.js
grunt/tasks/less.js

fixes [#362](https://github.com/adaptlearning/adapt-contrib-core/issues/362)
The process now applies defaults from the schema to the config.json where missing, then reads the values from the config and produces less and css variables from the name/values pairs in the config. Breakpoints are therefore no longer hardcoded.
* Breakpoints are derived from schema defaults and config

New: Breakpoints derived from schema defaults

---

grunt/tasks/less.js
grunt/tasks/schema-defaults.js

fixes #3412 
* Apply screenSize defaults after json copy rather than with less compile, as the json copy can overwrite the defaults from src/course > build/course

Fix: Apply screenSize defaults after json copy

---

grunt/tasks/server-build.js

fixes #3415 
* Apply schema defaults as a safeguard for AAT missing defaults

Fix: Apply schema defaults as a safeguard for AAT missing defaults

---

jsconfig.json

fixes #3419 
API autocomplete and deprecated highlighting should now work in jsx in Adapt in VSCode and other supporting editors.
* Update jsconfig.json for es2022 and jsx

Fix: Update jsconfig.json for es2022 and jsx

---

grunt/helpers.js

fixes #3447 
* Allow replace task to run specified as dev/prod using the `--dev` flag in the terminal

Fix: Allow replace task to run specified as dev/prod

---

grunt/tasks/tracking-insert.js

fixes #3464 
* Allow tracking ids without spoor installed

Fix: Allow tracking ids without spoor installed (fixes #3464)

---

grunt/tasks/build-config.js

fixes #3461 
* Removed paths from build.min.js

Fix: Remove paths from build.min.js (fixes #3461)

---

package-lock.json
test.js

Fixes #3502
* Wrapping Cypress run in try/catch to exit more gracefully
* Updated wait-on url to fix breaking listener when run in Node18

Fix: Wrapping Cypress run in try/catch to exit more gracefully (3502)

---

grunt/tasks/javascript.js

#3504 
* Re-ordered the existing logs to group the cache logs
* Added an extra log to the `javascript` task to print cache path (if enabled)
[//]: # (List appropriate steps for testing if needed)
1. Run any grunt task which includes the `javascript` task (any `build` will do)
[//]: # (Mention any other dependencies)

New: Add build cache path log (fixes #3504)

---

src/course/config.json
src/course/en/articles.json
src/course/en/blocks.json
src/course/en/components.json
src/course/en/contentObjects.json
src/course/en/course.json

With the add needed approach to updating the base JSON files, many of the base JSON fields have fallen out of sync with respective plug-in features. Adding them in would help raise awareness of what project teams can achieve out-of-the-box without having to figure out to reference example.json files or go to GitHub to read documentation. In fact, for others to know these features exist would encourage them to study up on them more.
* fixes: #3515 …

Update: Bringing base JSON files up-to-date (fixes: #3515)

---

.github/workflows/releases.yml
.github/workflows/test.yml

Addresses #3523
* Bumping versions for GHA packages

Chore: Bumping versions for GHA packages (3523)

---

grunt/helpers/plugins/Plugin.js

Fix #3526
* Adds the plugin name to the "unknown plugin type" error message
See #3526

Fix: Add plugin name to "unknown plugin type" error message (fixes #3526)

---

grunt/helpers/plugins/Plugin.js
package-lock.json
package.json

Fixes #3321
* Throws an error if required framework version in a plugin is not satisfied by the current framework version
1. In a plugin's _bower.json_, set `framework` to a high value like `>=7.0.0`

Fix: Warn if incompatible plugins are being compiled (fixes #3321)

---

src/course/en/course.json

Fix #3555 
* Adds `_navigation` and `_tooltips` objects to the sample [course](https://github.com/adaptlearning/adapt_framework/tree/master/src/course)

Fix: Add _navigation and _tooltips objects to sample course (fixes #3555)

---

src/course/en/components.json

Fixes #3566 
* Removes values for `_feedback._altTitle` in sample course. Keeps the property in place.
https://github.com/adaptlearning/adapt-contrib-core/pull/551

Fix: Remove values for _feedback._altTitle in sample course (fixes #3566)

---

.bowerrc

fixes https://github.com/adaptlearning/adapt_authoring/issues/2763
* Set default bower registry to secure http protocol

Fix: Default to secure connection for bower registry

---

test.js

Fixes #3588 
* Remove the forced lowercase in test params to permit camelcase directory name to be processed correctly

Fix: Remove the forced lowercase in test params to permit camelcase directory name to be processed correctly

---

grunt/helpers/CacheManager.js
grunt/tasks/javascript.js

Fixes #3599
Added this as a draft for now, as not sure if there was a specific reason for setting a custom cache path in the current way.
* Updates CacheManager's tempPath getter to pick up grunt.option('cachepath') - currently this is set externally outside of the CacheManager (in [tasks/javascript.js](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/javascript.js#L133))
[//]: # (List appropriate steps for testing if …

Fix: Refactor CacheManager to use cachepath grunt option internally (fixes #3599)

---

test.js
test/e2e/commands.js
test/e2e/helpers.js
test/e2e/trackingIds.cy.js

Addresses #3595 
* Function to populate cypress test spec if no argument value passed

Update: Function to populate cypress test spec if no argument value passed [3595]

---

test.js

Fixes #3608 
* Populating testfile globs that are specific to the current test runner

Fix: Populating testfile globs that are specific to the current test runner

---

src/course/config.json

Fix #3602 
* Adds `_theme` and `_menu` attributes to _config.json_. Without these, courses can break when importing into AAT v1.

Fix: Add _theme and _menu attributes to config.json (fixes #3602)

---

grunt/helpers/data/Language.js

fixes #3618 
* Correct double `//` using [`path.normalize`](https://nodejs.org/api/path.html#pathnormalizepath) which resolves incorrect truncation of file names here:
https://github.com/adaptlearning/adapt_framework/blob/49825341361c0e1bb3ac28344fe030b7380efefd/grunt/helpers/data/Language.js#L69

Fix: Support for node v23.0.0 (fixes #3618)

---

src/course/en/articles.json

Fix #3626 #3627
* Sets `_assessment._attempts` to the default value of `-1` instead of an invalid string value
* Sets `_trickle._onChildren` to true to match the behavior when the value is not explicitly set

Update: Update assessment article properties in sample course (fix #3626 #3627)

---

grunt/tasks/migration.js

* Pass the logger through the the test command

Fix: Reenable testing

---

grunt/tasks/migration.js

* Due to https://github.com/cgkineo/adapt-migrations/pull/22 supplementEntry is now no longer a passable option

Removed now unnecessary supplementEntry

---

README.md

* Removed forum links that have since been closed
* Removed Twitter link
* Update troubleshooting link to Gitter
Fixes https://github.com/adaptlearning/adapt_framework/issues/3636

Chore: Removed outdated communication links from README (fixes #3636)

---

grunt/helpers.js
grunt/helpers/Data.js
grunt/helpers/Framework.js
grunt/helpers/data/Language.js
grunt/helpers/data/LanguageFile.js
grunt/helpers/lib/JSONFile.js
grunt/tasks/migration.js

fixes #3667 
* Allow the task to be executed against any plugins and course-data
* Allow the task to specify a capture output and an outputdir for the migrated files
`--outputdir` changes away from `src/course` to a defined folder relative to the cwd, usually `build/` or an AAT temp folder for the course json and assets
`--capturedir` defaults to `./migrations/` and specifies where to write the capture output for migration
To capture the course-data `./src/course` and `./src/` plugins at `./migrations/`:
`$ grunt migration:capture`
To capture the course-data `./build/course` and `./src/` plugins at `./migrations/`:
`$ grunt migration:capture --outputdir=build/`
To capture the course-data `./build/course` and `./src/` plugins at `./captured/`:
`$ grunt migration:capture --outputdir=build/ …

New: Add --capturedir and --rootdir to grunt migration tasks (fixes #3667)

---

grunt/helpers/Framework.js

fixes #3671 
* Changed from path.join to path.resolve

Fix: Path resolution to root in migrations scripts (fixes #3671)

---

grunt/helpers/Framework.js

When changing from path.join to path.resolve the path is now being normalized and trailing slashes being removed.
#3675 
* ensure this.outputPath/sourcePath trailing slash isn't removed (fixes #3675)

Fix: ensure this.outputPath/sourcePath trailing slash isn't removed (fixes #3675)

---

grunt/config/watch.js
grunt/helpers.js

fixes #3649 
* Added timestamp to `build.min.js` to indicate file freshness in output build
* Force rebuild of `build.min.js` on `grunt dev`

New: Added timestamp to build.min.js
